In [1917]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [1918]:
sheet_id = "1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw"
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv"
df = pd.read_csv(url)

In [1919]:
df

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28237,10/13/2026 10:27:50,18-24,Health care,EMT,NaN,38334,NaN,USD,NaN,NaN,US,Michigan,"Flint, MI",2 - 4 years,1 year or less,NaN,NaN,NaN
28238,10/13/2026 13:02:00,18-24,"Accounting, Banking & Finance",Accountant,NaN,120000,NaN,USD,NaN,NaN,U.S,Michigan,Kalamazoo,1 year or less,1 year or less,High School,Man,NaN
28239,10/13/2026 13:23:11,18-24,Computing or Tech,Data scientist,NaN,120000,NaN,USD,NaN,NaN,United states.,Michigan,Detroit,1 year or less,1 year or less,College degree,Man,Black or African American
28240,10/13/2026 15:19:47,18-24,Hospitality & Events,Event staff,NaN,35000,NaN,USD,NaN,NaN,America,Florida,Naples,2 - 4 years,2 - 4 years,Some college,Man,White
28241,10/13/2026 15:27:13,18-24,Computing or Tech,student,NaN,0,NaN,USD,NaN,NaN,US,Michigan,East Lansing,2 - 4 years,2 - 4 years,High School,Man,Asian or Asian American

In [1920]:
df.columns

Index(['Timestamp', 'How old are you?', 'What industry do you work in?',
       'Job title',
       'If your job title needs additional context, please clarify here:',
       'What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)',
       'How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.',
       'Please indicate the currency',
       'If "Other," please indicate the currency here: ',
       'If your income needs additional context, please provide it here:',
       'What country do you work in?',
       'If you're in the U.S., what state do you work in?',
       'What city do you work in?',
       'How many years of professional work experience do you have overall?',
       'How many years of professional work experience do you have in your field?',
       'What is your highest level of education completed?',
       'What is your gender?', 'What is your race? (Choose all that apply.)'],
      dtype='str')

In [1921]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 28242 entries, 0 to 28241
Data columns (total 18 columns):
 #   Column                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                --------------  -----
 0   Timestamp                                                                                                                                                                                                                             28242 non-null  str
 1   How old are you?                                                                                                                                                                                                                      28242 non-null  str
 2   What industry do you work in?                                                                                                                                                                                                         28155 non-null  str
 3   Job title                                                                                                                                                                                                                             28236 non-null  str
 4   If your job title needs additional context, please clarify here:                                                                                                                                                                      7295 non-null   str
 5   What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)  28242 non-null  str
 6   How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                        20855 non-null  float64
 7   Please indicate the currency                                                                                                                                                                                                          28242 non-null  str
 8   If "Other," please indicate the currency here:                                                                                                                                                                                        227 non-null    str
 9   If your income needs additional context, please provide it here:                                                                                                                                                                      3053 non-null   str
 10  What country do you work in?                                                                                                                                                                                                          28240 non-null  str
 11  If you're in the U.S., what state do you work in?                                                                                                                                                                                     23162 non-null  str
 12  What city do you work in?                                                                                                                                                                                                             28157 non-null  str
 13  How many years of professional work experience do you have overall?                                                                                                                                                                   28242 non-null  str
 14  How many years of professional work experience do you have in your field?                                                                                                                                                             28242 non-null  str
 15  What is your highest level of education completed?                                                                                                                                                                                    27999 non-null  str
 16  What is your gender?                                                                                                                                                                                                                  28054 non-null  str
 17  What is your race? (Choose all that apply.)                                                                                                                                                                                           28042 non-null  str
dtypes: float64(1), str(17)
memory usage: 3.9 MB

In [1922]:
df.isna().sum()

Timestamp                                                                                                                                                                                                                                   0
How old are you?                                                                                                                                                                                                                            0
What industry do you work in?                                                                                                                                                                                                              87
Job title                                                                                                                                                                                                                                   6
If your job title needs additional context, please clarify here:                                                                                                                                                                        20947
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        0
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                           7387
Please indicate the currency                                                                                                                                                                                                                0
If "Other," please indicate the currency here:                                                                                                                                                                                          28015
If your income needs additional context, please provide it here:                                                                                                                                                                        25189
What country do you work in?                                                                                                                                                                                                                2
If you're in the U.S., what state do you work in?                                                                                                                                                                                        5080
What city do you work in?                                                                                                                                                                                                                  85
How many years of professional work experience do you have overall?                                                                                                                                                                         0
How many years of professional work experience do you have in your field?                                                                                                                                                                   0
What is your highest level of education completed?                                                                                                                                                                                        243
What is your gender?                                                                                                                                                                                                                      188
What is your race? (Choose all that apply.)                                                                                                                                                                                               200
dtype: int64

In [1923]:
df = df.drop_duplicates()

In [1924]:
columns_to_drop = [c for c in df.columns if "additional context" in c or "currency here" in c]
df = df.drop(columns=columns_to_drop)
df.columns

Index(['Timestamp', 'How old are you?', 'What industry do you work in?',
       'Job title',
       'What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)',
       'How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.',
       'Please indicate the currency', 'What country do you work in?',
       'If you're in the U.S., what state do you work in?',
       'What city do you work in?',
       'How many years of professional work experience do you have overall?',
       'How many years of professional work experience do you have in your field?',
       'What is your highest level of education completed?',
       'What is your gender?', 'What is your race? (Choose all that apply.)'],
      dtype='str')

In [1925]:
df["What is your race? (Choose all that apply.)"].unique()

<StringArray>
[                                                                                                                                                                                                                       'White',
                                                                                                                                                                                   'Hispanic, Latino, or Spanish origin, White',
                                                                                                                                                                                               'Asian or Asian American, White',
                                                                                                                                                                                                      'Asian or Asian American',
                                                                                                                                                                       'Another option not listed here or prefer not to answer',
                                                                                                                                                                                          'Hispanic, Latino, or Spanish origin',
                                                                                                                                                                                           'Middle Eastern or Northern African',
                                                                                                                                               'Hispanic, Latino, or Spanish origin, Middle Eastern or Northern African, White',
                                                                                                                                                                                                    'Black or African American',
                                                                                                                                                                                             'Black or African American, White',
                                                                                                                                                                                                                            nan,
                                                                                                                                                        'Black or African American, Hispanic, Latino, or Spanish origin, White',
                                                                                                                                                                                             'Native American or Alaska Native',
                                                                                                                                                                                      'Native American or Alaska Native, White',
                                                                                                                                  'Hispanic, Latino, or Spanish origin, Another option not listed here or prefer not to answer',
                                                                                                                       'Black or African American, Middle Eastern or Northern African, Native American or Alaska Native, White',
                                                                                                                                                                'White, Another option not listed here or prefer not to answer',
                                                                                                                                                           'Black or African American, Native American or Alaska Native, White',
                                                                                                                                              'Asian or Asian American, Another option not listed here or prefer not to answer',
                                                                                                                                                                                    'Middle Eastern or Northern African, White',
                                                                                                                                                                    'Asian or Asian American, Black or African American, White',
                                                                                                                                                               'Black or African American, Hispanic, Latino, or Spanish origin',
                                                                                                                                                                           'Asian or Asian American, Black or African American',
                                                                                                                                                          'Asian or Asian American, Hispanic, Latino, or Spanish origin, White',
                                                                                                                              'Native American or Alaska Native, White, Another option not listed here or prefer not to answer',
                                                                                                                                                                 'Asian or Asian American, Hispanic, Latino, or Spanish origin',
                                                                                                                                                             'Asian or Asian American, Native American or Alaska Native, White',
                                                                                                                                                        'Hispanic, Latino, or Spanish origin, Native American or Alaska Native',
                                                                                                                                                         'Black or African American, Middle Eastern or Northern African, White',
                                                                                                                      'Black or African American, Hispanic, Latino, or Spanish origin, Native American or Alaska Native, White',
                                                                                                                                            'Black or African American, Another option not listed here or prefer not to answer',
                                                                                                                                     'Native American or Alaska Native, Another option not listed here or prefer not to answer',
                                                                                                                                       'Asian or Asian American, White, Another option not listed here or prefer not to answer',
                                                                                                                                                                  'Asian or Asian American, Middle Eastern or Northern African',
                                                                                                                        'Asian or Asian American, Hispanic, Latino, or Spanish origin, Native American or Alaska Native, White',
                                                                                                                                                      'Hispanic, Latino, or Spanish origin, Middle Eastern or Northern African',
                                                                                                                                                 'Hispanic, Latino, or Spanish origin, Native American or Alaska Native, White',
                                                                                                                            'Middle Eastern or Northern African, White, Another option not listed here or prefer not to answer',
                                                                                                                           'Hispanic, Latino, or Spanish origin, White, Another option not listed here or prefer not to answer',
                                                                                                                                      'Asian or Asian American, Black or African American, Hispanic, Latino, or Spanish origin',
                                                                                                                                  'Asian or Asian American, Black or African American, Native American or Alaska Native, White',
                                                                                                                                                  'Middle Eastern or Northern African, Native American or Alaska Native, White',
                                                                                                                                                           'Asian or Asian American, Middle Eastern or Northern African, White',
                                                                                                                                                                'Black or African American, Middle Eastern or Northern African',
                                                                                                'Hispanic, Latino, or Spanish origin, Native American or Alaska Native, Another option not listed here or prefer not to answer',
                                                                                                                                                                    'Asian or Asian American, Native American or Alaska Native',
                                                                                                                                                         'Middle Eastern or Northern African, Native American or Alaska Native',
                                                                                                         'Asian or Asian American, Hispanic, Latino, or Spanish origin, Another option not listed here or prefer not to answer',
                                                                                                  'Asian or Asian American, Hispanic, Latino, or Spanish origin, White, Another option not listed here or prefer not to answer',
 'Asian or Asian American, Black or African American, Hispanic, Latino, or Spanish origin, Middle Eastern or Northern African, Native American or Alaska Native, White, Another option not listed here or prefer not to answer',
                                                                                                                                                                  'Black or African American, Native American or Alaska Native',
                                                                                                    'Asian or Asian American, Black or African American, Hispanic, Latino, or Spanish origin, Native American or Alaska Native',
                                                         'Asian or Asian American, Black or African American, Hispanic, Latino, or Spanish origin, Middle Eastern or Northern African, Native American or Alaska Native, White']
Length: 53, dtype: str

In [1926]:
df["What is your race? (Choose all that apply.)"].value_counts()

What is your race? (Choose all that apply.)
White                                                                                                                                                                                                                           23281
Asian or Asian American                                                                                                                                                                                                          1433
Black or African American                                                                                                                                                                                                         709
Another option not listed here or prefer not to answer                                                                                                                                                                            634
Hispanic, Latino, or Spanish origin                                                                                                                                                                                               613
Hispanic, Latino, or Spanish origin, White                                                                                                                                                                                        385
Asian or Asian American, White                                                                                                                                                                                                    345
Black or African American, White                                                                                                                                                                                                  123
Middle Eastern or Northern African, White                                                                                                                                                                                          83
Middle Eastern or Northern African                                                                                                                                                                                                 75
Native American or Alaska Native, White                                                                                                                                                                                            68
White, Another option not listed here or prefer not to answer                                                                                                                                                                      65
Native American or Alaska Native                                                                                                                                                                                                   43
Black or African American, Hispanic, Latino, or Spanish origin                                                                                                                                                                     28
Asian or Asian American, Hispanic, Latino, or Spanish origin, White                                                                                                                                                                15
Asian or Asian American, Hispanic, Latino, or Spanish origin                                                                                                                                                                       14
Black or African American, Hispanic, Latino, or Spanish origin, White                                                                                                                                                              11
Asian or Asian American, Another option not listed here or prefer not to answer                                                                                                                                                    11
Hispanic, Latino, or Spanish origin, Native American or Alaska Native                                                                                                                                                              11
Hispanic, Latino, or Spanish origin, Native American or Alaska Native, White                                                                                                                                                       10
Asian or Asian American, Black or African American                                                                                                                                                                                  9
Asian or Asian American, Middle Eastern or Northern African                                                                                                                                                                         7
Hispanic, Latino, or Spanish origin, Another option not listed here or prefer not to answer                                                                                                                                         6
Black or African American, Native American or Alaska Native, White                                                                                                                                                                  6
Asian or Asian American, Black or African American, White                                                                                                                                                                           6
Asian or Asian American, White, Another option not listed here or prefer not to answer                                                                                                                                              6
Hispanic, Latino, or Spanish origin, Middle Eastern or Northern African, White                                                                                                                                                      5
Black or African American, Middle Eastern or Northern African, White                                                                                                                                                                5
Asian or Asian American, Native American or Alaska Native, White                                                                                                                                                                    4
Black or African American, Hispanic, Latino, or Spanish origin, Native American or Alaska Native, White                                                                                                                             3
Native American or Alaska Native, White, Another option not listed here or prefer not to answer                                                                                                                                     2
Black or African American, Another option not listed here or prefer not to answer                                                                                                                                                   2
Hispanic, Latino, or Spanish origin, Middle Eastern or Northern African                                                                                                                                                             2
Middle Eastern or Northern African, White, Another option not listed here or prefer not to answer                                                                                                                                   2
Black or African American, Middle Eastern or Northern African                                                                                                                                                                       2
Asian or Asian American, Black or African American, Hispanic, Latino, or Spanish origin, Middle Eastern or Northern African, Native American or Alaska Native, White                                                                2
Black or African American, Middle Eastern or Northern African, Native American or Alaska Native, White                                                                                                                              1
Native American or Alaska Native, Another option not listed here or prefer not to answer                                                                                                                                            1
Asian or Asian American, Hispanic, Latino, or Spanish origin, Native American or Alaska Native, White                                                                                                                               1
Hispanic, Latino, or Spanish origin, White, Another option not listed here or prefer not to answer                                                                                                                                  1
Asian or Asian American, Black or African American, Hispanic, Latino, or Spanish origin                                                                                                                                             1
Asian or Asian American, Black or African American, Native American or Alaska Native, White                                                                                                                                         1
Middle Eastern or Northern African, Native American or Alaska Native, White                                                                                                                                                         1
Asian or Asian American, Middle Eastern or Northern African, White                                                                                                                                                                  1
Hispanic, Latino, or Spanish origin, Native American or Alaska Native, Another option not listed here or prefer not to answer                                                                                                       1
Asian or Asian American, Native American or Alaska Native                                                                                                                                                                           1
Middle Eastern or Northern African, Native American or Alaska Native                                                                                                                                                                1
Asian or Asian American, Hispanic, Latino, or Spanish origin, Another option not listed here or prefer not to answer                                                                                                                1
Asian or Asian American, Hispanic, Latino, or Spanish origin, White, Another option not listed here or prefer not to answer                                                                                                         1
Asian or Asian American, Black or African American, Hispanic, Latino, or Spanish origin, Middle Eastern or Northern African, Native American or Alaska Native, White, Another option not listed here or prefer not to answer        1
Black or African American, Native American or Alaska Native                                                                                                                                                                         1
Asian or Asian American, Black or African American, Hispanic, Latino, or Spanish origin, Native American or Alaska Native                                                                                                           1
Name: count, dtype: int64

In [1927]:
col = "What is your race? (Choose all that apply.)"
counts = df[col].value_counts()
filter100 = counts[counts > 100].index

df["Race"] = df[col].where(df[col].isin(filter100), "Other")
df = df.drop(columns=[col])
df["Race"].value_counts()

Race
White                                                     23281
Asian or Asian American                                    1433
Other                                                       719
Black or African American                                   709
Another option not listed here or prefer not to answer      634
Hispanic, Latino, or Spanish origin                         613
Hispanic, Latino, or Spanish origin, White                  385
Asian or Asian American, White                              345
Black or African American, White                            123
Name: count, dtype: int64

In [1928]:
df.head()

,Timestamp,How old are you?,What industry do you work in?,Job title,"What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,Race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,"55,000",0.0,USD,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,"54,600",4000.0,GBP,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,"34,000",NaN,USD,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,"62,000",3000.0,USD,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,"60,000",7000.0,USD,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

In [1929]:
df["What is your gender?"].value_counts()

What is your gender?
Woman                            21431
Man                               5573
Non-binary                         748
Other or prefer not to answer      301
Prefer not to answer                 1
Name: count, dtype: int64

In [1930]:
df["What is your gender?"] = df["What is your gender?"].replace("Prefer not to answer", "Other or prefer not to answer")
df["What is your gender?"].value_counts()

What is your gender?
Woman                            21431
Man                               5573
Non-binary                         748
Other or prefer not to answer      302
Name: count, dtype: int64

In [1931]:
df["What is your highest level of education completed?"].value_counts()

What is your highest level of education completed?
College degree                        13574
Master's degree                        8900
Some college                           2101
PhD                                    1428
Professional degree (MD, JD, etc.)     1331
High School                             665
Name: count, dtype: int64

In [1932]:
df["What is your highest level of education completed?"] = df["What is your highest level of education completed?"].replace("Some college", "College unfinished")
df["What is your highest level of education completed?"].value_counts()

What is your highest level of education completed?
College degree                        13574
Master's degree                        8900
College unfinished                     2101
PhD                                    1428
Professional degree (MD, JD, etc.)     1331
High School                             665
Name: count, dtype: int64

In [1933]:
df["How many years of professional work experience do you have in your field?"].value_counts()

How many years of professional work experience do you have in your field?
11 - 20 years       6548
5-7 years           6536
2 - 4 years         6302
8 - 10 years        4994
21 - 30 years       1875
1 year or less      1559
31 - 40 years        384
41 years or more      44
Name: count, dtype: int64

In [1934]:
df["How many years of professional work experience do you have in your field?"] = df["How many years of professional work experience do you have in your field?"].replace("5-7 years", "5 - 7 years")
df["How many years of professional work experience do you have in your field?"].value_counts()

How many years of professional work experience do you have in your field?
11 - 20 years       6548
5 - 7 years         6536
2 - 4 years         6302
8 - 10 years        4994
21 - 30 years       1875
1 year or less      1559
31 - 40 years        384
41 years or more      44
Name: count, dtype: int64

In [1935]:
df["How many years of professional work experience do you have overall?"].value_counts()

How many years of professional work experience do you have overall?
11 - 20 years       9645
8 - 10 years        5389
5-7 years           4904
21 - 30 years       3649
2 - 4 years         3078
31 - 40 years        871
1 year or less       577
41 years or more     129
Name: count, dtype: int64

In [1936]:
df["How many years of professional work experience do you have overall?"] = df["How many years of professional work experience do you have overall?"].replace("5-7 years", "5 - 7 years")
df["How many years of professional work experience do you have overall?"].value_counts()

How many years of professional work experience do you have overall?
11 - 20 years       9645
8 - 10 years        5389
5 - 7 years         4904
21 - 30 years       3649
2 - 4 years         3078
31 - 40 years        871
1 year or less       577
41 years or more     129
Name: count, dtype: int64

In [1937]:
df["What city do you work in?"].str.title().value_counts()

What city do you work in?
Boston         781
Chicago        760
New York       741
Seattle        700
London         585
              ...
Faisalabad       1
Pahang           1
Jalandhar        1
Northville       1
Flint, Mi        1
Name: count, Length: 4515, dtype: int64

In [1938]:
df["If you're in the U.S., what state do you work in?"].value_counts()

If you're in the U.S., what state do you work in?
California                                                                                                      2616
New York                                                                                                        2180
Massachusetts                                                                                                   1523
Texas                                                                                                           1272
Illinois                                                                                                        1213
                                                                                                                ...
Colorado, Delaware, New Jersey, West Virginia, Wyoming                                                             1
Utah, Wisconsin                                                                                                    1
Delaware, Louisiana                                                                                                1
Florida, Georgia                                                                                                   1
Idaho, Indiana, Iowa, Kansas, Kentucky, Louisiana, Maryland, Massachusetts, Michigan, Minnesota, Mississippi       1
Name: count, Length: 138, dtype: int64

In [1939]:
col = "If you're in the U.S., what state do you work in?"
counts = df[col].value_counts()
filter100 = counts[counts > 100].index

df[col] = df[col].where(df[col].isin(filter100) | df[col].isna(), "Other")
df[col].value_counts()

If you're in the U.S., what state do you work in?
California              2616
New York                2180
Massachusetts           1523
Texas                   1272
Illinois                1213
Washington              1185
Other                   1008
District of Columbia     983
Pennsylvania             946
Virginia                 786
Minnesota                723
Ohio                     656
Colorado                 634
Oregon                   626
North Carolina           602
Michigan                 589
Maryland                 565
Georgia                  552
Florida                  523
Wisconsin                470
New Jersey               401
Missouri                 345
Indiana                  329
Arizona                  305
Tennessee                286
Connecticut              239
Utah                     210
Kentucky                 192
Iowa                     180
Kansas                   155
South Carolina           148
Louisiana                129
Maine                    126
Alabama                  124
New Hampshire            118
Oklahoma                 113
Nebraska                 110
Name: count, dtype: int64

In [1940]:
df["What country do you work in?"].value_counts().head(15)

What country do you work in?
United States               9040
USA                         7966
US                          2622
Canada                      1576
United States                669
U.S.                         586
UK                           576
United Kingdom               551
USA                          468
Usa                          448
United States of America     431
Australia                    319
United states                209
usa                          187
Germany                      174
Name: count, dtype: int64

In [1941]:
import re
import unicodedata
import pycountry
from rapidfuzz import process, fuzz

In [1942]:
col = "What country do you work in?"

def norm(x):
    x = unicodedata.normalize("NFKD", str(x)).encode("ascii", "ignore").decode()
    x = x.lower().strip()
    x = x.replace(".", "")
    x = re.sub(r"[^a-z\s]", " ", x)
    return re.sub(r"\s+", " ", x).strip()

uniques = df[col].dropna().unique()
normalization_map = {u: norm(u) for u in uniques}

In [1943]:
aliases = {
    "us": "United States",
    "usa": "United States",
    "u s": "United States",
    "u s a": "United States",
    "america": "United States",
    "the united states": "United States",
    "uk": "United Kingdom", "u k": "United Kingdom",
    "england": "United Kingdom",
    "scotland": "United Kingdom",
    "wales": "United Kingdom",
    "northern ireland": "United Kingdom",
    "great britain": "United Kingdom",
    "the netherlands": "Netherlands",
    "holland": "Netherlands",
    "south korea": "South Korea",
    "korea": "South Korea",
    "russia": "Russia",
    "uae": "United Arab Emirates",
    "United State of America": "United States",
    "England, UK": "United Kingdom",
    "UnitedStates": "United States",
    "us": "United States",
    "ISA": "United States",
    "Scotland, UK": "United Kingdom",
    "United Sates of America": "United States",
    "Turkey": "Turkey",
    "The US": "United States",
    "UK (England)": "United Kingdom",
    "Brasil": "Brasil",
    "USA tomorrow": "United States",
    "USA-- Virgin Islands": "United States",
    "England/UK ": "United Kingdom",
    "England, UK.": "United Kingdom",    
    "Worldwide (based in US but short term trips aroudn the world)": "United States",
    "Canadw": "Canada",
    "I am located in Canada but I work for a company in the US": "United States",
    "Uniyes States": "United States",
    "Nederland": "Netherlands",
    "Englang": "United Kingdom"
    }

In [1944]:
std_names = {
    "United States": "United States",
    **{c.name: c.name for c in pycountry.countries}
}

common = {c.common_name: c.name for c in pycountry.countries if hasattr(
    c, "common_name")}

std_names.update(common)

all_countries = list(std_names.keys())

In [1945]:
display_names = {
    "Viet Nam": "Vietnam",
    "Taiwan, Province of China": "Taiwan",
    "Iran, Islamic Republic of": "Iran",
    "Korea, Republic of": "South Korea",
    "Russian Federation": "Russia",
    "Türkiye": "Turkey",
    "Czechia": "Czech Republic",
}

def match_country(raw):
    key = normalization_map[raw]
    if not key:
        return None, "empty"
    if key in aliases:
        name, how = aliases[key], "alias"
    else:
        try:
            name, how = pycountry.countries.lookup(key).name, "pycountry"
        except LookupError:
            r = process.extractOne(key.title(), all_countries, scorer=fuzz.WRatio, score_cutoff=90)
            if not r:
                return None, "unmatched"
            name, how = std_names[r[0]], f"fuzzy({r[1]:.0f})"
    return display_names.get(name, name), how

results = {u: match_country(u) for u in uniques}
mapping = {u: r[0] for u, r in results.items()}
method  = {u: r[1] for u, r in results.items()}

df["Country"] = df[col].map(mapping)

In [1946]:
df["method_check"] = df[col].map(method)
print(df["method_check"].str.replace(r"\(\d+\)", "", regex=True).value_counts(dropna=False))

method_check
pycountry    14433
alias        13587
fuzzy          122
unmatched       93
empty            5
NaN              2
Name: count, dtype: int64

In [1947]:
unmatched = df.loc[df["Country"].isna() & df[col].notna(), col].value_counts()
print(unmatched.head(40))
print("N of no matches:", unmatched.sum())

What country do you work in?
United State of America                                                                                                                                                                                              4
England, UK                                                                                                                                                                                                          4
UnitedStates                                                                                                                                                                                                         4
🇺🇸                                                                                                                                                                                                                   4
ISA                                                                                                                                                                                                                  3
Scotland, UK                                                                                                                                                                                                         3
United Sates of America                                                                                                                                                                                              2
Turkey                                                                                                                                                                                                               2
The US                                                                                                                                                                                                               2
Remote                                                                                                                                                                                                               2
UK (England)                                                                                                                                                                                                         2
Brasil                                                                                                                                                                                                               2
USA tomorrow                                                                                                                                                                                                         2
Contracts                                                                                                                                                                                                            1
USA-- Virgin Islands                                                                                                                                                                                                 1
England/UK                                                                                                                                                                                                           1
We don't get raises, we get quarterly bonuses, but they periodically asses income in the area you work, so I got a raise because a 3rd party assessment showed I was paid too little for the area we were located    1
England, UK.                                                                                                                                                                                                         1
Britain                                                                                                                                                                                                              1
Global                                                                                                                                                                                                               1
Worldwide (based in US but short term trips aroudn the world)                                                                                                                                                        1
Canadw                                                                                                                                                                                                               1
I am located in Canada but I work for a company in the US                                                                                                                                                            1
Uniyes States                                                                                                                                                                                                        1
US of A                                                                                                                                                                                                              1
Currently finance                                                                                                                                                                                                    1
UXZ                                                                                                                                                                                                                  1
Catalonia                                                                                                                                                                                                            1
$2,175.84/year is deducted for benefits                                                                                                                                                                              1
Virginia                                                                                                                                                                                                             1
USS                                                                                                                                                                                                                  1
Hartford                                                                                                                                                                                                             1
Csnada                                                                                                                                                                                                               1
UK for U.S. company                                                                                                                                                                                                  1
Cote d'Ivoire                                                                                                                                                                                                        1
England, Gb                                                                                                                                                                                                          1
Danmark                                                                                                                                                                                                              1
U.K. (northern England)                                                                                                                                                                                              1
Nederland                                                                                                                                                                                                            1
Englang                                                                                                                                                                                                              1
Name: count, dtype: int64
N of no matches: 98

In [1948]:
fuzzy = {u: (mapping[u], method[u]) for u in uniques if method[u].startswith("fuzzy")}
for u, (name, how) in fuzzy.items():
    print(f"{u!r:35} -> {name:25} {how}")

'United State'                      -> United States             fuzzy(96)
'United Stated'                     -> United States             fuzzy(92)
'United Statws'                     -> United States             fuzzy(92)
'Unites States '                    -> United States             fuzzy(92)
'United Sates'                      -> United States             fuzzy(96)
'Canada, Ottawa, ontario'           -> Canada                    fuzzy(90)
'United States of American '        -> United States             fuzzy(90)
'Uniited States'                    -> United States             fuzzy(96)
'United Kingdom (England)'          -> United Kingdom            fuzzy(90)
'United States (I work from home and my clients are all over the US/Canada/PR' -> United States             fuzzy(90)
'Unted States'                      -> United States             fuzzy(96)
'United Statesp'                    -> United States             fuzzy(96)
'United Stattes'                    -> United States             fuzzy(96)
'United Statea'                     -> United States             fuzzy(92)
'Unites States'                     -> United States             fuzzy(92)
'United Statees'                    -> United States             fuzzy(96)
'Uniyed states'                     -> United States             fuzzy(92)
'United States of Americas'         -> United States             fuzzy(90)
'United Kindom'                     -> United Kingdom            fuzzy(96)
'United Status'                     -> United States             fuzzy(92)
'Canda'                             -> Canada                    fuzzy(91)
'Canada and USA'                    -> Canada                    fuzzy(90)
'Italy (South)'                     -> Italy                     fuzzy(90)
'Jersey, Channel islands'           -> Jersey                    fuzzy(90)
'Uniteed States'                    -> United States             fuzzy(96)
'New Zealand Aotearoa'              -> New Zealand               fuzzy(90)
'Japan, US Gov position'            -> Japan                     fuzzy(90)
'United Stares'                     -> United States             fuzzy(92)
'Mainland China'                    -> China                     fuzzy(90)
'UK (Northern Ireland)'             -> Ireland                   fuzzy(90)
'Unites states '                    -> United States             fuzzy(92)
'Canad'                             -> Canada                    fuzzy(91)
'Unite States'                      -> United States             fuzzy(96)
'For the United States government, but posted overseas' -> United States             fuzzy(90)
'United Kingdomk'                   -> United Kingdom            fuzzy(97)
'Australi'                          -> Australia                 fuzzy(94)
'From Romania, but for an US based company' -> Romania                   fuzzy(90)
'Wales (United Kingdom)'            -> United Kingdom            fuzzy(95)
'England, United Kingdom'           -> United Kingdom            fuzzy(90)
'United statew'                     -> United States             fuzzy(92)
'The Bahamas '                      -> Bahamas                   fuzzy(90)
'United Statues'                    -> United States             fuzzy(96)
'Untied States'                     -> United States             fuzzy(92)
'Unitied States'                    -> United States             fuzzy(96)
'United Sttes'                      -> United States             fuzzy(96)
'Remote (philippines)'              -> Philippines               fuzzy(90)
'Unites kingdom '                   -> United Kingdom            fuzzy(93)
'united stated'                     -> United States             fuzzy(92)
'Austria, but I work remotely for a Dutch/British company' -> Austria                   fuzzy(90)
"I work for an US based company but I'm from Argentina." -> Argentina                 fuzzy(90)
'United Stateds'                    -> United States             fuzzy(96)
'Africa'                            -> Central African Republic  fuzzy(90)
'Luxemburg'                         -> Luxembourg                fuzzy(95)
'United Stares '                    -> United States             fuzzy(92)
'England, United Kingdom '          -> United Kingdom            fuzzy(90)
'United States- Puerto Rico'        -> United States             fuzzy(90)
'From New Zealand but on projects across APAC' -> New Zealand               fuzzy(90)
'Y'                                 -> Yemen                     fuzzy(90)
'Northern Ireland, United Kingdom'  -> United Kingdom            fuzzy(90)
'Australian '                       -> Australia                 fuzzy(95)
'United Statss'                     -> United States             fuzzy(92)
'ARGENTINA BUT MY ORG IS IN THAILAND' -> Argentina                 fuzzy(90)
'Aotearoa New Zealand'              -> New Zealand               fuzzy(90)
'United States is America'          -> United States             fuzzy(90)
'Company in Germany. I work from Pakistan.' -> Germany                   fuzzy(90)
'United States of American'         -> United States             fuzzy(90)
'Nigeria + UK'                      -> Nigeria                   fuzzy(95)

In [1949]:
ugly = [c for c in df["Country"].dropna().unique() if "," in c]
print(ugly)

['Tanzania, United Republic of']

In [1950]:
print(df["Country"].value_counts().head(15))
print("New nulls:", df["Country"].isna().sum() - df[col].isna().sum())

df = df.drop(columns="method_check")

Country
United States     23260
Canada             1691
United Kingdom     1583
Australia           392
Germany             199
New Zealand         132
Ireland             126
Netherlands          90
France               69
Spain                50
Sweden               41
Switzerland          38
Belgium              35
Japan                30
India                28
Name: count, dtype: int64
New nulls: 98

In [1951]:
counts = df["Country"].value_counts()
frequent = counts[counts > 100].index
df["Country"] = df["Country"].where(df["Country"].isin(frequent) | df["Country"].isna(), "Other")

In [1952]:
raw = "UnitedStates"          
print(repr(norm(raw)))                    
print(norm(raw) in aliases)               
print(match_country(raw))                 
print(df.loc[df[col] == raw, "Country"].unique())

'unitedstates'
False
(None, 'unmatched')
<StringArray>
[nan]
Length: 1, dtype: str

In [1953]:
aliases["unitedstates"] = "United States"
print("unitedstates" in aliases)      
print(match_country("UnitedStates"))

True
('United States', 'alias')

In [1954]:
aliases.update({
    "united state of america": "United States",
    "isa": "United States",
    "united sates of america": "United States",
    "the us": "United States",
    "uniyes states": "United States",
    "usa tomorrow": "United States",
    "england uk": "United Kingdom",
    "scotland uk": "United Kingdom",
    "uk england": "United Kingdom",
    "britain": "United Kingdom",
    "turkey": "Turkey",
    "brasil": "Brazil",
    "canadw": "Canada",
    "remote": "Other",
    "global": "Other",
    "contracts": "Other",
})
print("aliases:", len(aliases))

results = {u: match_country(u) for u in uniques}
mapping = {u: r[0] for u, r in results.items()}
method  = {u: r[1] for u, r in results.items()}
df["Country"] = df[col].map(mapping)

df.loc[df[col] == "🇺🇸", "Country"] = "United States"

unmatched = df.loc[df["Country"].isna() & df[col].notna(), col].value_counts()
print(unmatched.head(30))
print("N of no matches: ", unmatched.sum())

aliases: 56
What country do you work in?
🇺🇸                                                                                                                                                                                                                   4
USA-- Virgin Islands                                                                                                                                                                                                 1
We don't get raises, we get quarterly bonuses, but they periodically asses income in the area you work, so I got a raise because a 3rd party assessment showed I was paid too little for the area we were located    1
Worldwide (based in US but short term trips aroudn the world)                                                                                                                                                        1
I am located in Canada but I work for a company in the US                                                                                                                                                            1
US of A                                                                                                                                                                                                              1
Currently finance                                                                                                                                                                                                    1
UXZ                                                                                                                                                                                                                  1
Catalonia                                                                                                                                                                                                            1
$2,175.84/year is deducted for benefits                                                                                                                                                                              1
Virginia                                                                                                                                                                                                             1
USS                                                                                                                                                                                                                  1
Hartford                                                                                                                                                                                                             1
Csnada                                                                                                                                                                                                               1
UK for U.S. company                                                                                                                                                                                                  1
Cote d'Ivoire                                                                                                                                                                                                        1
England, Gb                                                                                                                                                                                                          1
Danmark                                                                                                                                                                                                              1
U.K. (northern England)                                                                                                                                                                                              1
Nederland                                                                                                                                                                                                            1
Englang                                                                                                                                                                                                              1
bonus based on meeting yearly goals set w/ my supervisor                                                                                                                                                             1
International                                                                                                                                                                                                        1
I earn commission on sales. If I meet quota, I'm guaranteed another 16k min. Last year i earned an additional 27k. It's not uncommon for people in my space to earn 100k+ after commission.                          1
USA (company is based in a US territory, I work remote)                                                                                                                                                              1
UK, remote                                                                                                                                                                                                           1
USAB                                                                                                                                                                                                                 1
I was brought in on this salary to help with the EHR and very quickly was promoted to current position but compensation was not altered.                                                                             1
Uniter Statez                                                                                                                                                                                                        1
n/a (remote from wherever I want)                                                                                                                                                                                    1
Name: count, dtype: int64
N of no matches:  59

In [1955]:
aliases.update({
    "us of a": "United States",
    "uss": "United States",
    "uniter statez": "United States",
    "csnada": "Canada",
    "usa virgin islands": "Other",
    "virginia": "United States",
    "hartford": "United States",

    "uk for us company": "United Kingdom",
    "england gb": "United Kingdom",
    "uk northern england": "United Kingdom",
    "englang": "United Kingdom",
    "cote d ivoire": "Cote d'Ivoire",
    "danmark": "Denmark",
    "nederland": "Netherlands",
    "catalonia": "Spain",
    "international": "Other",
    "worldwide based in us but short term trips aroudn the world": "Other",
    "n a remote from wherever i want": "Other",
    "uxz": "Other",
    "currently finance": "Other",
})
print("aliases:", len(aliases))

results = {u: match_country(u) for u in uniques}
mapping = {u: r[0] for u, r in results.items()}
method  = {u: r[1] for u, r in results.items()}
df["Country"] = df[col].map(mapping)
df.loc[df[col].str.contains("🇺🇸", na=False), "Country"] = "United States"

unmatched = df.loc[df["Country"].isna() & df[col].notna(), col].value_counts()
print(unmatched.head(30))
print("N of no matches: ", unmatched.sum())

aliases: 76
What country do you work in?
We don't get raises, we get quarterly bonuses, but they periodically asses income in the area you work, so I got a raise because a 3rd party assessment showed I was paid too little for the area we were located    1
I am located in Canada but I work for a company in the US                                                                                                                                                            1
$2,175.84/year is deducted for benefits                                                                                                                                                                              1
bonus based on meeting yearly goals set w/ my supervisor                                                                                                                                                             1
I earn commission on sales. If I meet quota, I'm guaranteed another 16k min. Last year i earned an additional 27k. It's not uncommon for people in my space to earn 100k+ after commission.                          1
USA (company is based in a US territory, I work remote)                                                                                                                                                              1
UK, remote                                                                                                                                                                                                           1
USAB                                                                                                                                                                                                                 1
I was brought in on this salary to help with the EHR and very quickly was promoted to current position but compensation was not altered.                                                                             1
US govt employee overseas, country withheld                                                                                                                                                                          1
San Francisco                                                                                                                                                                                                        1
Usat                                                                                                                                                                                                                 1
Unitef Stated                                                                                                                                                                                                        1
Wales, UK                                                                                                                                                                                                            1
USaa                                                                                                                                                                                                                 1
United y                                                                                                                                                                                                             1
Wales (UK)                                                                                                                                                                                                           1
europe                                                                                                                                                                                                               1
California                                                                                                                                                                                                           1
UK, but for globally fully remote company                                                                                                                                                                            1
USD                                                                                                                                                                                                                  1
USA, but for foreign gov't                                                                                                                                                                                           1
I work for a UAE-based organization, though I am personally in the US.                                                                                                                                               1
Policy                                                                                                                                                                                                               1
hong konh                                                                                                                                                                                                            1
London                                                                                                                                                                                                               1
dbfemf                                                                                                                                                                                                               1
ibdia                                                                                                                                                                                                                1
LOUTRELAND                                                                                                                                                                                                           1
ff                                                                                                                                                                                                                   1
Name: count, dtype: int64
N of no matches:  35

In [1956]:
aliases.update({
    "usab": "United States",
    "usat": "United States",
    "usaa": "United States",
    "unitef stated": "United States",
    "united y": "United States",
    "usa but for foreign gov t": "United States",
    "usa company is based in a us territory i work remote": "United States",
    "san francisco": "United States",
    "california": "United States",

    "uk remote": "United Kingdom",
    "wales uk": "United Kingdom",
    "wales": "United Kingdom",
    "uk but for globally fully remote company": "United Kingdom",

    "usd": "Other",
    "europe": "Other",
    "ff": "Other",
    "loutreland": "Other",
    "us govt employee overseas country withheld": "Other",
})
print("aliases:", len(aliases))


results = {u: match_country(u) for u in uniques}
mapping = {u: r[0] for u, r in results.items()}
method  = {u: r[1] for u, r in results.items()}
df["Country"] = df[col].map(mapping)

df.loc[df[col].str.contains("🇺🇸", na=False), "Country"] = "United States"

long_text = df[col].str.len() > 40
df.loc[long_text & df["Country"].isna(), "Country"] = "Other"

unmatched = df.loc[df["Country"].isna() & df[col].notna(), col].value_counts()
print(unmatched.to_string())
print("N of no matches: ", unmatched.sum())

aliases: 93
What country do you work in?
$2,175.84/year is deducted for benefits    1
Policy                                     1
hong konh                                  1
London                                     1
dbfemf                                     1
ibdia                                      1
Burma                                      1
Česká republika                            1
Italia                                     1
Hong KongKong                              1
1                                          1
N of no matches:  11

In [1957]:
aliases.update({
    "hong konh": "Hong Kong",
    "hong kongkong": "Hong Kong",
    "london": "United Kingdom",
    "burma": "Myanmar",
    "ceska republika": "Czech Republic",   
    "italia": "Italy",
    "ibdia": "India",                       
    "policy": "Other",
    "dbfemf": "Other",
    "year is deducted for benefits": "Other",
})
print("aliases:", len(aliases))


results = {u: match_country(u) for u in uniques}
mapping = {u: r[0] for u, r in results.items()}
method  = {u: r[1] for u, r in results.items()}
df["Country"] = df[col].map(mapping)


df.loc[df[col].str.contains("🇺🇸", na=False), "Country"] = "United States"

long_text = df[col].str.len() > 40
df.loc[long_text & df["Country"].isna(), "Country"] = "Other"


empty_norm = df[col].notna() & (df[col].map(lambda x: norm(x) if pd.notna(x) else "") == "")
df.loc[empty_norm & df["Country"].isna(), "Country"] = "Other"


unmatched = df.loc[df["Country"].isna() & df[col].notna(), col].value_counts()
print(unmatched.to_string())
print("N of no matches: ", unmatched.sum())

aliases: 103
Series([], )
N of no matches:  0

In [1958]:
import json
with open("country_mapping.json", "w", encoding="utf-8") as f:
    json.dump(mapping, f, ensure_ascii=False, indent=2)

In [1959]:
df.head(5)

,Timestamp,How old are you?,What industry do you work in?,Job title,"What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,Race,Country
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,"55,000",0.0,USD,United States,Massachusetts,Boston,5 - 7 years,5 - 7 years,Master's degree,Woman,White,United States
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,"54,600",4000.0,GBP,United Kingdom,NaN,Cambridge,8 - 10 years,5 - 7 years,College degree,Non-binary,White,United Kingdom
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,"34,000",NaN,USD,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White,United States
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,"62,000",3000.0,USD,USA,Wisconsin,Milwaukee,8 - 10 years,5 - 7 years,College degree,Woman,White,United States
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,"60,000",7000.0,USD,US,South Carolina,Greenville,8 - 10 years,5 - 7 years,College degree,Woman,White,United States

In [1960]:
df["Please indicate the currency"].value_counts()

Please indicate the currency
USD        23512
CAD         1677
GBP         1598
EUR          654
AUD/NZD      505
Other        178
CHF           37
SEK           37
JPY           23
ZAR           17
HKD            4
Name: count, dtype: int64

In [1961]:
col = "Please indicate the currency"

counts = df[col].value_counts()
frequent = counts[counts > 100].index

df["Currency"] = df[col].where(df[col].isin(frequent) | df[col].isna(), "Other")

print(df["Currency"].value_counts(dropna=False))

Currency
USD        23512
CAD         1677
GBP         1598
EUR          654
AUD/NZD      505
Other        296
Name: count, dtype: int64

In [1962]:
df["How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits."].value_counts()

How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.
0.0          7981
5000.0       1117
10000.0       964
2000.0        778
1000.0        680
             ...
35553.0         1
299.0           1
11.0            1
60.0            1
2500000.0       1
Name: count, Length: 850, dtype: int64

In [1963]:
df["What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)"].value_counts()

What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)
60,000    430
80,000    406
70,000    402
65,000    400
75,000    383
         ...
21          1
148800      1
26          1
7500        1
38334       1
Name: count, Length: 4337, dtype: int64

In [1964]:
col = "What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)"

df["Salary"] = pd.to_numeric(
    df[col].astype(str).str.replace(r"[,\s$]", "", regex=True),
    errors="coerce",
)
df[col].value_counts()

What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)
60,000    430
80,000    406
70,000    402
65,000    400
75,000    383
         ...
21          1
148800      1
26          1
7500        1
38334       1
Name: count, Length: 4337, dtype: int64

In [1965]:
failed = df.loc[df["Salary"].isna() & df[col].notna(), col]
print(len(failed))
print(failed.value_counts().head(20))

0
Series([], Name: count, dtype: int64)

In [1966]:
print(df["Salary"].describe())
print(df["Salary"].nsmallest(15).tolist())
print(df["Salary"].nlargest(15).tolist())

count    2.824200e+04
mean     3.709770e+05
std      3.612279e+07
min      0.000000e+00
25%      5.400000e+04
50%      7.500000e+04
75%      1.094875e+05
max      6.000070e+09
Name: Salary, dtype: float64
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[6000070000, 870000000, 180000000, 140000000, 120000000, 102000000, 96000000, 52200000, 43800000, 38000000, 36000000, 27000000, 24000000, 20800000, 11500000]

In [1967]:
df = df.drop(columns=[col])

In [1968]:
df["Salary"]

0         55000
1         54600
2         34000
3         62000
4         60000
          ...
28237     38334
28238    120000
28239    120000
28240     35000
28241         0
Name: Salary, Length: 28242, dtype: int64

In [1969]:
df.head()

,Timestamp,How old are you?,What industry do you work in?,Job title,"How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,Race,Country,Currency,Salary
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,0.0,USD,United States,Massachusetts,Boston,5 - 7 years,5 - 7 years,Master's degree,Woman,White,United States,USD,55000
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,4000.0,GBP,United Kingdom,NaN,Cambridge,8 - 10 years,5 - 7 years,College degree,Non-binary,White,United Kingdom,GBP,54600
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,USD,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White,United States,USD,34000
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,3000.0,USD,USA,Wisconsin,Milwaukee,8 - 10 years,5 - 7 years,College degree,Woman,White,United States,USD,62000
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,7000.0,USD,US,South Carolina,Greenville,8 - 10 years,5 - 7 years,College degree,Woman,White,United States,USD,60000

In [1970]:
df["Job title"].value_counts()

Job title
Software Engineer           287
Project Manager             230
Director                    198
Senior Software Engineer    196
Program Manager             153
                           ...
Bartender                     1
Biotechnology                 1
Undergraduate Researcher      1
checker, bagger               1
Event staff                   1
Name: count, Length: 14445, dtype: int64

In [1971]:
from sklearn.feature_extraction.text import CountVectorizer

titles = (df["Job title"].dropna().str.lower().str.replace(r"[^a-z\s]", " ", regex=True).str.strip())

cv = CountVectorizer(stop_words="english", ngram_range=(1,2), min_df=20)
X = cv.fit_transform(titles)

freq = pd.Series(X.sum(axis=0).A1, index=cv.get_feature_names_out())
print(freq.sort_values(ascending=False).head(60))

manager                5442
senior                 2960
director               2631
engineer               2218
assistant              1745
analyst                1710
software               1312
associate              1312
specialist             1195
coordinator            1069
software engineer       896
marketing               873
project                 847
program                 743
research                626
data                    615
operations              609
executive               598
development             571
product                 549
consultant              549
project manager         542
lead                    534
developer               506
business                505
teacher                 480
hr                      463
communications          463
librarian               460
officer                 429
scientist               428
designer                413
editor                  395
technical               395
sr                      370
attorney                370
support                 350
staff                   347
engineering             345
program manager         344
administrator           342
administrative          341
services                332
sales                   332
supervisor              327
senior software         326
customer                315
professor               312
digital                 308
marketing manager       296
account                 286
office                  285
executive assistant     277
systems                 261
advisor                 260
writer                  258
ii                      254
content                 252
product manager         248
management              241
dtype: int64

In [1972]:
rules = [
    ("Education & Library",  r"instructional design|teacher|professor|instructor|librarian|archivist|lecturer|academic|school|faculty|tutor|curator"),
    ("Healthcare",           r"nurse|\brn\b|\bnp\b|doctor|physician|clinical|medical|therapist|pharmac|dental|health"),
    ("Social & Public Service", r"social worker|case manager|caseworker|counselor|program officer|policy"),
    ("Data & Analytics",     r"data|analyst|analytics|\bbi\b|statistic"),
    ("Software & IT",        r"software|developer|programmer|devops|\bit\b|systems|network|security|product owner|product manager|\bux\b|\bqa\b"),
    ("Engineering",          r"engineer"),
    ("Research & Science",   r"research|scientist|\blab\b|biolog|chemist"),
    ("Writing & Media",      r"editor|writer|copywriter|reporter|journalist|content|producer|communications"),
    ("Design",               r"design|illustrator|creative"),
    ("Marketing & Sales",    r"market|sales|account exec|account manager|brand|business development|\bpr\b"),
    ("Finance & Legal",      r"controller|accountant|accounting|finance|financial|auditor|attorney|lawyer|legal|counsel|paralegal|banker|tax"),
    ("Customer Service",     r"customer service|customer success|support specialist|client service"),
    ("HR",                   r"\bhr\b|human resources|recruit|talent"),
    ("Admin & Support",      r"admin|assistant|coordinator|receptionist|clerk|secretary"),
    ("Consulting",           r"consultant|advisor"),
    ("Operations & Project", r"operations|project|program manager|logistics|supply chain|procurement"),
    ("General Management",   r"manager|director|\bvp\b|president|chief|\bc[a-z]o\b|supervisor|head of|partner"),
]

In [1973]:
def update_rule(name, pattern):
    for i, (n, p) in enumerate(rules):
        if n == name:
            rules[i] = (n, pattern)
            return
    raise ValueError(f"Rule {name} does not exist")

update_rule("Education & Library",
    r"instructional design|teacher|professor|instructor|librarian|library|archivist|lecturer|academic|school|faculty|tutor|curator|student")

update_rule("Data & Analytics",
    r"data|analyst|analytics|\bbi\b|business intelligence|statistic")


update_rule("Software & IT",
    r"software|developer|programmer|devops|\bit\b|systems|network|security|product owner|product manager|\bqa\b")

update_rule("Design",
    r"design|illustrator|creative|\bux\b|art director")

update_rule("Marketing & Sales",
    r"market|sales|account exec|account manager|brand|business development|\bpr\b|social media")

update_rule("Finance & Legal",
    r"controller|accountant|accounting|finance|financial|auditor|attorney|lawyer|legal|counsel|paralegal|banker|tax|payroll")

update_rule("HR",
    r"\bhr\b|human resources|recruit|talent|people operations|people partner")

update_rule("Admin & Support",
    r"office manager|(?<!director of )admin|assistant(?! (?:\w+ )?(?:director|manager))|coordinator|receptionist|clerk|secretary")

In [1974]:
def job_family(title):
    if pd.isna(title):
        return np.nan
    t = title.lower()
    for name, pattern in rules:
        if re.search(pattern, t):
            return name
    return "Other"

df["Job title"] = df["Job title"].str.strip()
uniq = df["Job title"].dropna().unique()
fam_map = {u: job_family(u) for u in uniq}
df["job_family"] = df["Job title"].map(fam_map)

print(df["job_family"].value_counts(dropna=False))

job_family
General Management         4009
Other                      3708
Software & IT              2564
Admin & Support            2203
Data & Analytics           2179
Education & Library        2073
Finance & Legal            1752
Writing & Media            1506
Marketing & Sales          1415
Operations & Project       1335
Engineering                1288
Healthcare                  936
Research & Science          824
HR                          809
Design                      519
Consulting                  498
Social & Public Service     318
Customer Service            300
NaN                           6
Name: count, dtype: int64

In [1975]:
print(df.loc[df["job_family"] == "Other", "Job title"].value_counts().head(40))

Job title
Associate                      108
Senior Associate                51
Team Lead                       23
Bookkeeper                      17
Team Leader                     17
Geologist                       17
Development Associate           16
Epidemiologist                  16
Development Officer             16
Architect                       16
Economist                       15
Registrar                       15
Buyer                           15
Veterinarian                    14
Compliance Officer              13
Planner                         13
Program Specialist              13
Solution Architect              13
Psychologist                    13
Program Associate               12
Technician                      12
Solutions Architect             12
Speech Language Pathologist     11
Specialist                      11
Environmental Specialist        11
Translator                      10
EA                              10
Trainer                          9
Archaeologist                    9
Investigator                     9
Barista                          9
Scrum Master                     8
Owner                            8
Contract Specialist              7
Registered Dietitian             7
Tech Lead                        7
Principal                        7
HRBP                             7
Public Defender                  7
Cashier                          7
Name: count, dtype: int64

In [1976]:
import requests

df["date"] = pd.to_datetime(df["Timestamp"], format="%m/%d/%Y %H:%M:%S", errors="coerce").dt.normalize()
print(df["date"].min(), df["date"].max())

df["Currency"] = df["Please indicate the currency"]
df.loc[df["Currency"] == "AUD/NZD", "Currency"] = df["Country"].map({"Australia": "AUD", "New Zealand": "NZD"})

2021-04-27 00:00:00 2026-10-13 00:00:00

In [1977]:
start, end = df["date"].min().date(), df["date"].max().date()
symbols = ["CAD", "GBP", "EUR", "AUD", "NZD", "CHF", "SEK", "JPY", "ZAR", "HKD"]

r = requests.get(
    f"https://api.frankfurter.dev/v1/{start}..{end}",
    params={"base": "USD", "symbols": ",".join(symbols)},
    timeout=30,
)
r.raise_for_status()

rates = pd.DataFrame(r.json()["rates"]).T
rates["USD"] = 1.0
rates.to_csv("fx_rates_2021.csv")

In [1978]:
df["survey_year"] = df["date"].dt.year

n0 = len(df)
df = df[df["survey_year"] == 2021].copy()
print(f"Eliminated rows: {n0 - len(df)} ({(n0 - len(df)) / n0:.1%})")
print("Remaining rows:", len(df))

Eliminated rows: 645 (2.3%)
Remaining rows: 27597

In [1979]:
extra = "How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits."
df = df.rename(columns={extra: "Additional_comp"})

fx = rates.mean()                              
df["fx_per_usd"] = df["Currency"].map(fx)

df["Salary_USD"] = df["Salary"] / df["fx_per_usd"]
df["Additional_comp_USD"] = df["Additional_comp"] / df["fx_per_usd"]
df["Total_comp_USD"] = df["Salary_USD"] + df["Additional_comp_USD"].fillna(0)

print("Not converted:", df["Salary_USD"].isna().sum())
print(df.loc[df["Salary_USD"].isna(), "Currency"].value_counts(dropna=False))

Not converted: 144
Currency
Other    142
NaN        2
Name: count, dtype: int64

In [1980]:
print(df["Salary_USD"].quantile([.001, .01, .05, .5, .95, .99, .999]).round(0))
print(df["Salary_USD"].nsmallest(15).round(0).tolist())
print(df["Salary_USD"].nlargest(15).round(0).tolist())

0.001        40.0
0.010     20031.0
0.050     33280.0
0.500     74298.0
0.950    180000.0
0.990    264480.0
0.999    817536.0
Name: Salary_USD, dtype: float64
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 20.0, 33.0]
[102000000.0, 5000044.0, 3000000.0, 2111538.0, 1900000.0, 1650000.0, 1334782.0, 1300000.0, 1260000.0, 1250000.0, 1225398.0, 1200000.0, 1173802.0, 1134757.0, 1100000.0]

In [1981]:
df = df[df["Salary_USD"] > 999].copy()
print(df["Salary_USD"].nsmallest(10).round(0).to_list)

<bound method IndexOpsMixin.tolist of 19536    1000.0
16980    1442.0
18823    1630.0
21245    1934.0
26890    2350.0
17547    2400.0
12907    2653.0
3933     2814.0
12017    2838.0
14075    3200.0
Name: Salary_USD, dtype: float64>

In [1982]:
df["Total_comp_USD"].head(10).sort_values(ascending=True)

2     34000.000000
6     35000.000000
9     45000.000000
7     50000.000000
0     55000.000000
5     62000.000000
3     65000.000000
4     67000.000000
1     75587.712423
8    122000.000000
Name: Total_comp_USD, dtype: float64

In [1983]:
df.head(5)

,Timestamp,How old are you?,What industry do you work in?,Job title,Additional_comp,Please indicate the currency,What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,...,Country,Currency,Salary,job_family,date,survey_year,fx_per_usd,Salary_USD,Additional_comp_USD,Total_comp_USD
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,0.0,USD,United States,Massachusetts,Boston,5 - 7 years,...,United States,USD,55000,Education & Library,2021-04-27,2021,1.000000,55000.000000,0.000000,55000.000000
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,4000.0,GBP,United Kingdom,NaN,Cambridge,8 - 10 years,...,United Kingdom,GBP,54600,Writing & Media,2021-04-27,2021,0.775258,70428.141609,5159.570814,75587.712423
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,USD,US,Tennessee,Chattanooga,2 - 4 years,...,United States,USD,34000,Marketing & Sales,2021-04-27,2021,1.000000,34000.000000,NaN,34000.000000
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,3000.0,USD,USA,Wisconsin,Milwaukee,8 - 10 years,...,United States,USD,62000,Operations & Project,2021-04-27,2021,1.000000,62000.000000,3000.000000,65000.000000
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,7000.0,USD,US,South Carolina,Greenville,8 - 10 years,...,United States,USD,60000,Finance & Legal,2021-04-27,2021,1.000000,60000.000000,7000.000000,67000.000000

In [1984]:
col = "What industry do you work in?"
df[col].value_counts().sort_values(ascending=False).head(25)

What industry do you work in?
Computing or Tech                       4550
Education (Higher Education)            2425
Nonprofits                              2379
Government and Public Administration    1859
Health care                             1844
Accounting, Banking & Finance           1765
Engineering or Manufacturing            1649
Marketing, Advertising & PR             1092
Law                                     1083
Business or Consulting                   827
Education (Primary/Secondary)            818
Media & Digital                          758
Insurance                                522
Retail                                   486
Recruitment or HR                        446
Property or Construction                 377
Utilities & Telecommunications           346
Art & Design                             344
Transport or Logistics                   296
Sales                                    279
Social Work                              265
Hospitality & Events                     252
Entertainment                            247
Agriculture or Forestry                  135
Leisure, Sport & Tourism                  97
Name: count, dtype: int64

In [1985]:
counts = df[col].value_counts()
filter100 = counts[counts > 100].index
df["Industry"] = df[col].where(df[col].isin(filter100) | df[col].isna(), "Other")
df["Industry"].value_counts()

Industry
Computing or Tech                       4550
Education (Higher Education)            2425
Nonprofits                              2379
Other                                   2249
Government and Public Administration    1859
Health care                             1844
Accounting, Banking & Finance           1765
Engineering or Manufacturing            1649
Marketing, Advertising & PR             1092
Law                                     1083
Business or Consulting                   827
Education (Primary/Secondary)            818
Media & Digital                          758
Insurance                                522
Retail                                   486
Recruitment or HR                        446
Property or Construction                 377
Utilities & Telecommunications           346
Art & Design                             344
Transport or Logistics                   296
Sales                                    279
Social Work                              265
Hospitality & Events                     252
Entertainment                            247
Agriculture or Forestry                  135
Name: count, dtype: int64

In [1986]:
df.isna().sum()

Timestamp                                                                       0
How old are you?                                                                0
What industry do you work in?                                                  68
Job title                                                                       0
Additional_comp                                                              7075
Please indicate the currency                                                    0
What country do you work in?                                                    0
If you're in the U.S., what state do you work in?                            4746
What city do you work in?                                                      78
How many years of professional work experience do you have overall?             0
How many years of professional work experience do you have in your field?       0
What is your highest level of education completed?                            199
What is your gender?                                                          164
Race                                                                            0
Country                                                                         0
Currency                                                                        0
Salary                                                                          0
job_family                                                                      0
date                                                                            0
survey_year                                                                     0
fx_per_usd                                                                      0
Salary_USD                                                                      0
Additional_comp_USD                                                          7075
Total_comp_USD                                                                  0
Industry                                                                       68
dtype: int64

In [1987]:
df.columns

Index(['Timestamp', 'How old are you?', 'What industry do you work in?',
       'Job title', 'Additional_comp', 'Please indicate the currency',
       'What country do you work in?',
       'If you're in the U.S., what state do you work in?',
       'What city do you work in?',
       'How many years of professional work experience do you have overall?',
       'How many years of professional work experience do you have in your field?',
       'What is your highest level of education completed?',
       'What is your gender?', 'Race', 'Country', 'Currency', 'Salary',
       'job_family', 'date', 'survey_year', 'fx_per_usd', 'Salary_USD',
       'Additional_comp_USD', 'Total_comp_USD', 'Industry'],
      dtype='str')

In [1988]:
col = "If you're in the U.S., what state do you work in?"
df[col] = df[col].fillna(df["Country"].map(lambda country: "Unknown" if country == "United States" else "Non-US"))

In [1989]:
df[col].value_counts()

If you're in the U.S., what state do you work in?
Non-US                  4577
California              2561
New York                2138
Massachusetts           1506
Texas                   1233
Illinois                1188
Washington              1170
District of Columbia     973
Other                    971
Pennsylvania             931
Virginia                 771
Minnesota                708
Ohio                     642
Colorado                 621
Oregon                   621
North Carolina           594
Maryland                 548
Michigan                 537
Georgia                  515
Florida                  513
Wisconsin                461
New Jersey               391
Missouri                 330
Indiana                  320
Arizona                  298
Tennessee                279
Connecticut              234
Utah                     204
Kentucky                 185
Iowa                     177
Unknown                  169
Kansas                   148
South Carolina           143
Louisiana                129
Maine                    124
New Hampshire            116
Alabama                  114
Oklahoma                 113
Nebraska                 108
Name: count, dtype: int64

In [1990]:
df.columns

Index(['Timestamp', 'How old are you?', 'What industry do you work in?',
       'Job title', 'Additional_comp', 'Please indicate the currency',
       'What country do you work in?',
       'If you're in the U.S., what state do you work in?',
       'What city do you work in?',
       'How many years of professional work experience do you have overall?',
       'How many years of professional work experience do you have in your field?',
       'What is your highest level of education completed?',
       'What is your gender?', 'Race', 'Country', 'Currency', 'Salary',
       'job_family', 'date', 'survey_year', 'fx_per_usd', 'Salary_USD',
       'Additional_comp_USD', 'Total_comp_USD', 'Industry'],
      dtype='str')

In [1991]:
drop_cols = [
    "date", "survey_year", "fx_per_usd",
    "What industry do you work in?",                      
    "What country do you work in?",                      
    "Please indicate the currency",                                                                 
]
rename_cols = {
    "How old are you?": "age",
    "Job title": "job_title",
    "What city do you work in?": "city",
    "How many years of professional work experience do you have overall?": "exp_overall",
    "How many years of professional work experience do you have in your field?": "exp_field",
    "What is your highest level of education completed?": "education",
    "What is your gender?": "gender",
    "Race": "race",
    "Country": "country",
    "If you're in the U.S., what state do you work in?": "state",
    "Industry": "industry",
    "Currency": "currency_original",
    "Salary": "salary_local",
    "Additional_comp": "additional_comp_local",
    "Salary_USD": "salary_usd",
    "Additional_comp_USD": "additional_comp_usd",
    "Total_comp_USD": "total_comp_usd",
}
df = df.drop(columns=drop_cols).rename(columns=rename_cols)

In [1992]:
df.head(5)

,Timestamp,age,job_title,additional_comp_local,state,city,exp_overall,exp_field,education,gender,race,country,currency_original,salary_local,job_family,salary_usd,additional_comp_usd,total_comp_usd,industry
0,4/27/2021 11:02:10,25-34,Research and Instruction Librarian,0.0,Massachusetts,Boston,5 - 7 years,5 - 7 years,Master's degree,Woman,White,United States,USD,55000,Education & Library,55000.000000,0.000000,55000.000000,Education (Higher Education)
1,4/27/2021 11:02:22,25-34,Change & Internal Communications Manager,4000.0,Non-US,Cambridge,8 - 10 years,5 - 7 years,College degree,Non-binary,White,United Kingdom,GBP,54600,Writing & Media,70428.141609,5159.570814,75587.712423,Computing or Tech
2,4/27/2021 11:02:38,25-34,Marketing Specialist,NaN,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White,United States,USD,34000,Marketing & Sales,34000.000000,NaN,34000.000000,"Accounting, Banking & Finance"
3,4/27/2021 11:02:41,25-34,Program Manager,3000.0,Wisconsin,Milwaukee,8 - 10 years,5 - 7 years,College degree,Woman,White,United States,USD,62000,Operations & Project,62000.000000,3000.000000,65000.000000,Nonprofits
4,4/27/2021 11:02:42,25-34,Accounting Manager,7000.0,South Carolina,Greenville,8 - 10 years,5 - 7 years,College degree,Woman,White,United States,USD,60000,Finance & Legal,60000.000000,7000.000000,67000.000000,"Accounting, Banking & Finance"

In [1993]:
print(df.shape)

(27361, 19)

In [1994]:
print(df.columns.to_list())

['Timestamp', 'age', 'job_title', 'additional_comp_local', 'state', 'city', 'exp_overall', 'exp_field', 'education', 'gender', 'race', 'country', 'currency_original', 'salary_local', 'job_family', 'salary_usd', 'additional_comp_usd', 'total_comp_usd', 'industry']

In [1995]:
city_map = {
    "washington dc": "Washington DC", "washington, dc": "Washington DC",
    "washington, dc.": "Washington DC", "washington, d.c.": "Washington DC",
    "washington, district of columbia": "Washington DC",
    "dc": "Washington DC", "district of columbia": "Washington DC",
    "washington": "Washington DC",

    "new york": "New York City", "new york city": "New York City",
    "nyc": "New York City", "ny metro": "New York City",
    "nyc (remotely)": "New York City", "westchester/nyc": "New York City",
    "brooklyn": "New York City", "manhattan": "New York City",

    "st. paul": "Saint Paul", "st paul": "Saint Paul", "st paul, mn": "Saint Paul",
    "st. louis": "Saint Louis", "st louis": "Saint Louis",

    "boston, ma": "Boston", "arlington, va": "Arlington", "omaha, ne": "Omaha",
    "springfield, il": "Springfield", "columbia, sc": "Columbia",
    "harrisonburg, va": "Harrisonburg", "albany, ny": "Albany",
    "tallahassee, fl": "Tallahassee", "charlotte, nc": "Charlotte",
    "jersey city, nj": "Jersey City", "san jose, ca": "San Jose",
    "walnut creek, california": "Walnut Creek", "plattsburgh, ny": "Plattsburgh",
    "toronto, on": "Toronto", "calgary ab": "Calgary",
    "kitchener, ontario": "Kitchener", "london, on can": "London",
    "waterloo, on": "Waterloo", "cornwall, ontario": "Cornwall",

    "greater boston area": "Boston", "metro boston": "Boston",
    "fully remote (greater boston)": "Boston",
    "philadelphia (suburbs)": "Philadelphia", "philadelphia suburbs": "Philadelphia",
    "greater philadelphia area": "Philadelphia", "philly 'burbs": "Philadelphia",
    "suburb of chicago": "Chicago", "suburban chicago": "Chicago",
    "chicago (remote)": "Chicago", "remote (chicago)": "Chicago",
    "greater chicago": "Chicago",
    "chicago area mostly, but also the us and canada": "Chicago",
    "atlanta metro area": "Atlanta", "houston area": "Houston",
    "detroit metro area": "Detroit", "durham area": "Durham",
    "ann arbor area": "Ann Arbor", "baltimore suburbs": "Baltimore",
    "denver metro area": "Denver",
    "albany-schenectady-troy metro area": "Albany",
    "greater new orleans metro region": "New Orleans",
    "huntington (remote, hq is in charleston)": "Huntington",
    "las vegas (techinically remote)": "Las Vegas",
    "dfw": "Dallas-Fort Worth", "dfw area": "Dallas-Fort Worth",
    "dallas/fort worth region": "Dallas-Fort Worth",
    "bay area": "San Francisco Bay Area",
    "research triangle": "Research Triangle",
    "research triangle region": "Research Triangle",
    "twin cities metro area": "Twin Cities", "twin cities suburbs": "Twin Cities",

    "witchita": "Wichita", "minnespolis": "Minneapolis",
    "shaker hts": "Shaker Heights", "la": "Los Angeles",

    "northeast florida": np.nan, "north east": np.nan, "panhandle region": np.nan,
    "south texas": np.nan, "central kentucky": np.nan, "northwest georgia": np.nan,
    "western mass": np.nan, "gorham/portland": np.nan, "naval base": np.nan,

    "remote": np.nan, "remote worker": np.nan, "remote/ home": np.nan,
    "i work remotely": np.nan, "work from home": np.nan,
    "remote (live in nottingham)": np.nan,
    "full time remote from my home near a major pa city": np.nan,
    "prefer not to answer": np.nan, "prefer not to say": np.nan,
    "prefer not to disclose": np.nan, "would rather not say": np.nan,
    "decline to answer": np.nan, "too identifiable": np.nan,
    "this is too identifying": np.nan, "prefer not to say (montana is small!)": np.nan,
    "no city": np.nan, "no": np.nan, "none": np.nan,
    "verysmall town": np.nan, "semirural city": np.nan,
    "small city, remote, national company": np.nan,
    "<br><br>": np.nan,
}

In [1996]:
city_map.update({

    "st. paul": "Saint Paul",
    "st paul": "Saint Paul",
    "st paul, mn": "Saint Paul",
    "saint paul": "Saint Paul",

    "st. louis": "Saint Louis",
    "st louis": "Saint Louis",
    "saint louis": "Saint Louis",

   
    "newcastle, uk": "Newcastle",

    "victoria, bc, canada": "Victoria",
    "victoria, bc": "Victoria",
    "chilliwack, bc": "Chilliwack",
    "chilliwack, bc, canada": "Chilliwack",
    "st. john's": "St. John's",
    "st john's": "St. John's",
    "st. johns": "St. John's",
    "st johns": "St. John's",

  
    "research triangle": "Other",
    "research triangle region": "Other",
    "raleigh-durham": "Other",
    "raleigh durham": "Other",

    "twin cities": "Other",
    "twin cities metro area": "Other",
    "twin cities suburbs": "Other",

    "san francisco bay area": "Other",
    "bay area": "Other",

    "dallas-fort worth": "Other",
    "dfw": "Other",
    "dfw area": "Other",
    "dallas/fort worth region": "Other",

    "rural ontario": "Other",
    "ontario": "Other",

  
    "eglin afb": "Other",
    "**too small a sample size, can't share": "Other",

    "-": "Other",
    "---": "Other",
    "-----": "Other",
    "/": "Other",

    "a suburb of boston": "Boston",
    "a very large city": "Other",

    "abington pa": "Abington",
    "abington, pa": "Abington",

    "acton, ma": "Acton",
    "An Exact Answer Would Out Me": "Other",
    "Bc": "Other",
    "Belmont, Ca (Sf Bay Area)": "Belmont",
    "Bend, Or": "Other",
    "Berlin (Remote For Us Clients)": "Berlin",
    "Birmingham, AI": "Birmingham",
    "Birmingham, England": "Birmingham",
    "Birmingham, Uk": "Birmingham",
    "Bloomington, In": "Bloomington",
    "Boston(Ish)": "Boston",
    "Boston Area": "Boston",
    "Boston Ma": "Boston",
    "Boston Massachusetts": "Boston",
    "Boston Suburbs": "Boston",
    "Calgary, Ab": "Calgary",
    "Cambridge ,Ma": "Cambridge",
    "Cambridge, Ma": "Cambridge",
    "Can'T Share": "Other",
    "Chantilly, Va": "Chantilly",
    "Chester Springs, Pa": "Chester Springs",
    "Cheyenne, Wy": "Cheyenne",
    "Chicago (Suburbs)": "Chicago",
    "Chicago Area": "Chicago",
    "Chicago But The Company Is Remote": "Chicago",
    "Chicago Suburbs": "Chicago",
    "Chilliwack, Bc": "Chilliwack",
    "Cincinnati": "Oh",
    "Company Is Based In Nashville, I Work Remotely From Nyc": "Other",
    "Company Is In Nyc, I'M Remote In Boston": "Other",
    "D.C.": "Other",
    "Dallas-Fort Worth": "Dallas",
    "Dc Metro Area": "Other",
    "Decline To Mention": "Other",
    "Decline To Provide": "Other",
    "Denver (But Remote - Company Is Nyc)": "Other",
    "Derby, Ct": "Derby",
    "Detroit Metro": "Detroit",
    "Detroit, Mi": "Detroit",
    "Dont Want To Say": "Other",
    "Drop Down Menur Was Not Working. Indianapolis Indiana.": "Other",
    "Durham, Nc": "Durham",
    "Eastern Ma (Not Boston)": "Other",
    "Edmonton, Alberta": "Edmonton",
    "Egg Harbor Twp": "Other",
    "Eglin Afb": "Other",
    "Estevan, Saskatchewan": "Other",
    "Fairfax County": "Fairfax",
    "Fairfield County": "Fairfield",
    "Findlay, Oh": "Other",
    "Framingham, Ma": "Other",
    "Ft Lauderdale": "Other",
    "Ft. Lauderdale": "Other",
    "Ft. Mitchell": "Other",
    "Full Time Remote Employee (Prior To Pandemic)": "Other",
    "Fully Remote Job (Denver Area)": "Other",
    "Geismar, La": "Other",
    "Georgian Bay Area": "Other",
    "Gloucester, Gloucestershire": "Other",
    "Gloucestershire (V. Rural Place Of Work)": "Other",
    "Greater Nashville Area": "Other",
    "Greater Toronto Area": "Other",
    "Greenfield, Ma": "Greenfield",
    "Hamilton, On": "Hamilton",
    "Harrisburg Area": "Harrisburg",
    "Henrico, Va": "Henrico",
    "Home": "Other",
    "Home/Remote": "Other",
    "Houston, But The Job Is Remote": "Houston",
    "Houston-Galveston-Brazoria Area": "Houston",
    "Hudson, Ny": "Other",
    "Iowa City (Coralville)": "Other",
    "Job Is Based In Dc, But I Go To Where The Disasters Are": "Other",
    "Kansas City, Mo": "Kansas",
    "Kelowna, Bc": "Kelowna",
    "Lincoln, Ne": "Lincoln",
    "Long Island (Remote)": "Long Island",
    "Los A6": "Other",
    "Los Angeles Metro": "Los Angeles",
    "Major Metro Area": "Other",
    "Major State Metro Area": "Other",
    "Manchester, Uk": "Manchester",
    "Martinez (Bay Area)": "Other",
    "Mcol New England": "Other",
    "Mid-Size City": "Other",
    "Milford, Massachussets": "Other",
    "Milwaukee Area": "Milwaukee",
    "Milwaukee Metro Area": "Milwaukee",
    "Minneapolis Suburbs": "Minneapolis",
    "Minneapolis, Wfh": "Minneapolis",
    "Mon, Ontario": "Other",
    "My City + Industry Would Id My Employer": "Other",
    "N/A": "Other",
    "N/A - County": "Other",
    "N/A Cloud-Based": "Other",
    "Na": "Other",
    "Na (Remote). Live Near Boston, Work Is Based In Upstate Ny": "Other",
    "Near Ann Arbor": "Other",
    "New City, Ny": "Other",
    "New York City/Manhattan": "New York City",
    "New York City, Ny": "New York City",
    "New Castle Upon Tyne": "New Castle",
    "New Castle , Uk": "New Castle",
    "Newport Beach": "Newport",
    "Newport News": "Newport",
    "Newton Square": "Other",
    "Niagara Falls": "Other",
    "Norman, Ok": "Norman",
    "North Chicago": "Chicago",
    "North Andover": "Other",
    "Noth Of Boston": "Other",
    "North Port": "Other",
    "Northern B.C.": "Other",
    "Northern CO": "Other",
    "Northern Front Range": "Other",
    "Northern Michigan": "Other",
    "Northern Va": "Other",
    "Not Disclosing": "Other",
    "Not Identifying, But The Central Valley, Ca": "Other",
    "Nottingham, Uk": "Nottingham",
    "Nyc (But I Work Remote)": "New York City",
    "Nyc - Queens": "New York City",
    "Orange County- San Diego County": "San Diego",
    "Orange, Ma": "Orange",
    "Oregon City": "Oregon",
    "Orlando Metro Area": "Orlando",
    "Ottawa, Ontario": "Ottawa",
    "Pascagoula, Ms": "Pascagoula",
    "Payroll Is Out Of Cincinnati": "Cincinnati",
    "Peabody, Ma": "Peabody",
    "Philedelphia": "Philadelphia",
    "Pittsburgh, Pa": "Pittsburgh",
    "Plymouth Meeting": "Plymouth",
    "Pooler, Ga": "Pooler",
    "Port Carling, Muskoka, Ontario": "Other",
    "Portland Area": "Portland",
    "Portland, Me": "Portland",
    "Portland, Me Area": "Portland",
    "Portland, Or (Remote For A Company In Ca)": "Portland",
    'Primary Wfh Or Nyc; However Travel To Client Site Weekly In The "Before Times"': "New York City",
    "Puget Sound Region": "Other",
    "Rapid City": "Other",
    "Raleigh Nc": "Raleigh",
    "Rather Not Answer": "Other",
    "Radwood City, Ca": "Radwook City",
    "Reading": "Other",
    "Regina, Sk": "Regina",
    "Remote (Org Based Out Of Dc Metro Area)": "Other",
    "Remote But Nyc": "New York City",
    "Remote Position": "Other",
    "Remote Work From Home": "Other",
    "Remote Work; Ontario-Wide": "Ontario",
    "Remote; Based Out Of Houston": "Hudson",
    "Rochester, Ny": "New York City",
    "Rochester Hills": "Rochester",
    "Rural": "Other",
    "Rural - Northern": "Other",
    "Rural Area": "Other",
    "Rural Area, Remote Worker": "Other",
    "Rural College Town": "Other",
    "Rural Florida Panhandle": "Other",
    "Rural Ontario": "Ontario",
    "Rural Small Town Western Ny": "Other",
    "Rural Southwest England": "Other",
    "Sacramento, Ca": "Sacramento",
    "Salem, Ma": "Salem",
    "Salk Lake City": "Other",
    "San Carlos, Ca": "San Carlos",
    "San Francisco Bay Area": "San Francisco",
    "Schaumburg (Chicago Metro Area)": "Schaumburg",
    "Scheanectady, Ny": "New York City",
    "Scheanectady": "New York City",
    "Scotland, Ont": "Other",
    "Seattle, Wa": "Seattle",
    "Seattle, Washington": "Seattle",
    "Sf": "San Francisco",
    "Sf Bay Area": "San Francisco",
    "Small City": "Other",
    "Small City In Sw Uk": "Other",
    "Small Town": "Other",
    "Small Town, Cornwall": "Other",
    "South East England": "Other",
    "South San Francisco": "San Francisco",
    "Southern II": "Other",
    "Southern Maryland": "Maryland",
    "Torrance, Ca": "Torrance",
    "Vancouver Area": "Vancouver",
    "Vancouver, B.C.": "Vancouver",
    "Vancouver, Bc": "Vancouver",
    "Various": "Other",
    "Warwick, Ri": "Warwick",
    "White River Junction, Vt": "Other",
    "Winston-Salem": "Winston",
    "Worcester Area": "Worcester",
    "Work Across The Whole State": "Other",
    "Would Give Too Much Away": "Other",
    "Would Rather Not Answer ( Would Be Very Easy To Figure Out Who I Am)": "Other",
    "York": "New York City",
    "York Region": "New York City",
    "A City Small Enough To Not Answer This Question": "Other",
    "Aldie Va": "Aldie",
    "Alexandria Va": "Alexandria",
    "Allen, Tx": "Allen",
    "An Exact Answer Would Out Me": "Other",
    "Asheville, Nc": "Asheville",
    "Baltimore County": "Baltimore",
    "Baltimore Suburb": "Baltimore",
    "Baltimore, Md": "Baltimore",
    "Baltimore (But I Work Fully Remotely)": "Baltimore",
    "Bc": "Other",
    "A Small City": "Other",
    "Aldie, Va": "Vancouver",
    "Albuquerqur": "Albuquerque",
    "Aliso Viejo": "Other",
    "Allendale, Mi": "Allendale",
    "Austin Metro Area": "Austin",
    "Big Bear City": "Other",
    "Birmingham, Al": "Birmingham",
    "Work From Home": "Other",
    "Would Rather Not Say": "Other",
    "Wilkes-Barre": "Wilkes",
    "Wilmington, Nc": "Wilmington",
    "Wfh": "Other",
    "Wfh Kenilworth": "Other",
    "Whistler, Bc": "Other",
    "Western Ks": "Other",
    "Western Mass": "Other",
    "Western Slope": "Other",
    "West Roxbury": "Other",
    "West Palm Beaxh": "Palm Beach",
    "West Palm Beach": "Palm Beach",
    "West Des Moines": "Other",
    "West Bend": "Other",
    "West Lafayette": "Other",
    "Wayne, Pa": "Other",
    "Watertown": "Other",
    "Washington D.C.": "Washington DC",
    "Washington D.C": "Washington DC",
    "Washington, D.C": "Washington DC",
    "Walnut Creek": "Other",
    "Verysmall Town": "Other",
    "Vancouver Island": "Vancouver",
    "Utah County": "Other",
    "Upper Valley": "Other",
    "Upstate Ny": "New York City",
    "United Kingdom": "Other",
    "Uk": "Other",
    "Tucson, Az": "Tucson",
    "Travelling Over All Of Europe": "Other",
    "Toronto, For A Global Remote Company": "Toronto",
    "Toronto, Ontario": "Toronto",
    "Toronto, Ontario, Canada": "Toronto",
    "Toronto On": "Toronto",
    "Too Identificable": "Other",
    "This Is Too Identifying": "Other",
    "This Info Will Make Me Identifiable": "Other",
    "This Identifies My Employer": "Other",
    "Takoma Park, Md": "Takoma",
    "Surrey Bc": "Surrey",
    "Suburban Nyc Metro Area": "New York City",
    "Suburb Of Philadelphia": "Philadelphia",
    "Stillwater: Wi Based Company, Office In Mn": "Other",
    "Steinbach, Manitoba": "Other",
    "St Petersburg": "St. Petersburg",
    "St Clair Shores": "St. Clair Shores",
    "St Thomas": "St. Thomas",
    "St Catharines": "St. Catharines",
    "Southern Mn": "Other",
    "Souther II": "Other",
    "Southend-On-Sea": "Other",
    "South Texas": "Other",
    "Socal, Prefer Not To Specify": "Other",
    "Small Town Called Reigate, In Surrey Just Outside London": "London",
    "Small City, Remote, National Company": "Other",
    "Scranton/Wilkes-Barre": "Scranton",
    "Schenectady, Ny": "Schenectady",
    "Rural New England": "Other",
    "Rural College Comunnity": "Other",
    "Rural Iowa": "Iowa",
    "Central Il": "Other",
    "Central Kentucky": "Kentucky",
    "Centrail Maine": "Other",
    "Central Md": "Other",
    "Central Nj": "Other",
    "Central Pa": "Other",
    "Company Is In Glendale, California I Am In Barrie, Ontario": "Other",
    "Semirural City": "Other",
    "Waskesiu Lake": "Other",
    "Waltham, Ma": "Waltham",
    "Virginia Beach": "Virginia",
    "Prefer Not To Answer": "Other",
    "Prefer Not To Say (Montana Is Small!)": "Other",
    "Prefer Not To Disclose": "Other",
    "Prefer Not To Say": "Other",
    "Western Canada": "Other",
    "Anonymous": "Other",
    "Raleigh (Remote Out Of Va)": "Other",
    "Rural College Community": "Other",
    "Federal Way": "Other",
    "Rocklin (Sacramento Area)": "Rocklin",
    "Remote (Live In Nottingham)": "Other",
    "I Work Remotely": "Other",
    "Remote/ Home": "Other",
    "Full Time Remote From My Home Near A Major Pa City": "Other",
    "Remote; Based Out Of Hudson": "Hudson",
    "Park City (Remote/Wfh)": "Other",
    "Remote - Lansdale": "Lansdale",
    "Remote Employee Pre-Pandemic": "Other",
    "Na (Remote)": "Other",
    "Remote Worker": "Other",
    "Saint Louis": "St. Louis",
    "Remote": "Other",
    "Saint Paul": "St. Paul",
    "Plant City": "Other",
    "Gorham/Portland": "Portland",
    "Decline To Answer": "Other",
    "St. Paul/Minniapolis Area": "Minneapolis",
    "Oklahoma City": "Oklahoma",
    "Job Is Based In Dc, But I Go To Where Disasters Are": "Other",
    "St. Thomas, Usvi": "St. Thomas",
    "Menomonee Falls": "Menomonee",
    "New York, Ny": "New York City",
    "Gloucester, Gloucestershire.": "Gloucester",
    "Currently Remote": "Other",
    "Newcastle Upon Tyne": "New Castle",
    "Midwest Area": "Other",
    "Southern Il": "Other",
    "Dripping Springs": "Other",
    "Milford, Massachusetts": "Other",
    "Regina (Sk)": "Regina",
    "Montreal, Qc": "Montreal",
    "Cherry Hill, Nj": "Cherry Hill",
    "Kitchener, On": "Kitchener",
    "Joppatowne (Near Baltimore, Md)": "Baltimore",
    "Few Hours Outside Columbus": "Other",
    "Ft Myers": "Other",
    "Stockholm. But Also From Italy (Online Work). Or Anywhere Actually.": "Stockholm",
    "Macon, Ga": "Macon",
    "Newcastle Upon Tyne": "New Castle",
    "Large Metro Area": "Other",
    "Newark, Nj": "Other",
    "Xxx": "Other",
    "I'M Permanently Remote In Ma, Company Is Global.": "Other",
    "Remote--Don'T Work In Same State As My Employer Is Located": "Other",
    "Denver Metro": "Denver",
    "Egg Harbor Township": "Other",
    "Evanston, Il": "Evanston",
    "London, Uk": "London",
    "Menomonee Falls": "Menomonee",
    "King Of Prussia": "Other",
    "Decline To Answer": "Other",
    "State College": "Other",
    "Choose Not To Answer": "Other",
    "Minneapolis-St Paul": "Other",
    "Daytona Beach": "Daytona",
    "--": "Other",
    "Redwood City, Ca": "Other",
    "Norman,Ok": "Norman",
    "See Above": "Other",
    "Cincinnati, Oh": "Cincinnati",
    "Greater Cleveland": "Cleveland",
    "Kansas City Region": "Kansas City",
    "Columbia Md": "Columbia",
    "Medium Size City": "Other",
    "Chicagoland Area": "Chicago",
    "Chicagoland": "Chicago",
    "Greater Seattle Area": "Seattle",
    "New York City/Brooklyn": "New York City",
    "Dallas-Ft Worth": "Dallas",
    "Madison, Wi": "Madison",
    "Marlborough Ma": "Marlborough",
    "Linthicum, Md": "Linthicum",
    "Minneapolis/St Paul": "Minneapolis",
    "Elgin, Illinois": "Elgin",
    "Greater Vancouver": "Vancouver",
    "Hermosillo, Sonora": "Hermosillo",
    "Cambridge Ma": "Cambridge",
    "Based On Current Client Project": "Other",
    "Burlington, Ma": "Burlington",
    "Ft Meade": "Other",
    "Madison, Wi": "Madison",
    "Augusta Il": "Augusta",
    "Newtown Square": "Newtown",
    "Northeast": "Florida",
    "Too Identifiable": "Other",
    "Panhandle Region": "Other",
    "(Anonymous)": "Other",
    ".": "Other",
    "12043": "Other",
    "46901": "Other",
    "60K Small City": "Other",
    "A Major One": "Other",
    "0000":  "Other",
    "Aberdeen Proving Ground": "Aberdeen",
    "Affluen Chicago Suburb": "Chicago",
    "Alexandria, La": "Alexandria",
    "Alexandria, Va": "Alexandria",
    "Alexandrira": "Alexandria",
    "All Over N Ca": "Other",
    "Allen/Plano": "Allen",
    "Allen Park": "Allen",
    "Alpharetta, Ga": "Alpharetta",
    "Amherst, Ma": "Amherst",
    "Ann Arborn, Michigan": "Ann Arborn",
    "Austin / New York": "Austin",
    "Austin, Texas": "Austin",
    "Austin, Tx": "Austin",
    "Baltimore Area": "Baltimore",
    "Baltimore Metro": "Baltimore",
    "Baltimore Metro Region, Md": "Baltimore",
    "Baltimore Mariland": "Baltimore"

})

In [1997]:
city_map = {str(k).lower().strip(): v for k, v in city_map.items()}

c = (
    df["city"]
    .astype(str)
    .str.replace(r"<.*?>", "", regex=True)
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

low = c.str.lower()
df["city"] = low.map(city_map).fillna(c.str.title())

print(df["city"].value_counts().head(25))

city
New York City    1690
Washington DC     999
Chicago           868
Boston            867
Seattle           748
Other             689
San Francisco     639
London            618
Los Angeles       534
Portland          492
Toronto           440
Minneapolis       389
Philadelphia      361
Austin            356
Atlanta           348
Denver            337
Houston           276
Vancouver         255
Pittsburgh        241
Dallas            233
Cambridge         224
Madison           193
Columbus          191
San Diego         184
Baltimore         177
Name: count, dtype: int64

In [1998]:
title_map = {
    "rn": "RN", "cpa": "CPA", "csr": "Customer Service Representative",
    "np-phc": "Nurse Practitioner", "svp, risk management": "SVP, Risk Management",
    "vp of communications": "VP of Communications", "vp of communication": "VP of Communications",
    "tech writer": "Technical Writer", "technical writer": "Technical Writer",

    "sr associate - quality assurance": "Senior Associate - Quality Assurance",
    "sr. piping designer": "Senior Piping Designer",
    "sr analytic consultant": "Senior Analytic Consultant",
    "sr. environmental manager": "Senior Environmental Manager",
    "sr development manager": "Senior Development Manager",
    "sr. database analyst": "Senior Database Analyst",
    "sr business analyst": "Senior Business Analyst",
    "sr. corporate recruiter": "Senior Corporate Recruiter",
    "sr institutional research analyst": "Senior Institutional Research Analyst",
    "sr. project coordinator": "Senior Project Coordinator",
    "sr technical support rep": "Senior Technical Support Representative",
    "sr. product manager": "Senior Product Manager",
    "sr. project manager": "Senior Project Manager",
    "sr sourcing specialist": "Senior Sourcing Specialist",
    "sr. document control specialist": "Senior Document Control Specialist",
    "sr technical program manager": "Senior Technical Program Manager",
    "sr executive assistant": "Senior Executive Assistant",

    "finance acountant": "Finance Accountant",
    "graduate research assitant": "Graduate Research Assistant",
    "assistent front office manager": "Assistant Front Office Manager",
    "network managet": "Network Manager",
    "principle product marketing manager": "Principal Product Marketing Manager",

    "software engineer": "Software Engineer", "software developer": "Software Developer",
    "senior software engineer": "Senior Software Engineer", "web developer": "Web Developer",
    "developer": "Developer", "systems analyst": "Systems Analyst",
    "programmer analyst": "Programmer Analyst", "data analyst": "Data Analyst",
    "ux designer": "UX Designer", "senior ux designer": "Senior UX Designer",
    "user experience specialist": "UX Specialist", "ux specialist": "UX Specialist",
    "it director": "IT Director", "director of it": "IT Director",
    "director of information technology": "IT Director",


    "hr manager": "HR Manager", "human resources manager": "HR Manager",
    "hr director": "HR Director", "human resources director": "HR Director",
    "hr business partner": "HR Business Partner",
    "hr adviser": "HR Advisor", "senior people advisor": "Senior People Advisor",


    "admin assistant": "Administrative Assistant", "administrative assistant": "Administrative Assistant",
    "senior administrative assistant": "Senior Administrative Assistant",
    "executive assistant": "Executive Assistant", "legal secretary": "Legal Secretary",
    "office admin": "Office Administrator", "office administrator": "Office Administrator",
    "office manager": "Office Manager", "administrator": "Administrator",

    "attorney": "Attorney", "staff attorney": "Staff Attorney", "associate attorney": "Associate Attorney",
    "paralegal": "Paralegal", "paralegal / legal assistant": "Paralegal", "legal assistant": "Legal Assistant",

    "teacher": "Teacher", "high school teacher": "High School Teacher",
    "9-12 grade teacher": "High School Teacher",
    "high school teacher at an independent school": "High School Teacher",
    "librarian": "Librarian", "librarian, non-supervisory": "Librarian",
    "information professional (librarian)": "Librarian", "children's librarian": "Children's Librarian",
    "professor": "Professor", "assistant professor": "Assistant Professor",
    "associate professor": "Associate Professor",
    "graduate student": "Graduate Student", "phd candidate": "PhD Candidate",
    "research assistant": "Research Assistant", "teaching assistant": "Teaching Assistant",
    "instructional designer": "Instructional Designer", "academic advisor": "Academic Advisor",
    "archivist": "Archivist",


    "nurse practitioner": "Nurse Practitioner", "public defender": "Public Defender",
    "speech-language pathologist": "Speech-Language Pathologist",
    "speech language pathologist": "Speech-Language Pathologist",
    "physician (fm)": "Physician", "staff physician": "Physician",

   
    "accounting manager": "Accounting Manager", "senior accountant": "Senior Accountant",
    "staff accountant": "Staff Accountant", "tax accountant": "Tax Accountant",
    "controller": "Controller", "bookkeeper": "Bookkeeper", "bookkeeper self-employed": "Bookkeeper",
    "finance manager": "Finance Manager", "financial analyst": "Financial Analyst",
    "payroll manager": "Payroll Manager", "investment advisor": "Investment Advisor",
    "billing & accounts receivable specialist": "Billing & Accounts Receivable Specialist",

    "marketing manager": "Marketing Manager", "marketing specialist": "Marketing Specialist",
    "marketing director": "Marketing Director", "digital marketing specialist": "Digital Marketing Specialist",
    "communications specialist": "Communications Specialist",
    "communications manager": "Communications Manager", "communication manager": "Communications Manager",
    "internal communications specialist": "Internal Communications Specialist",
    "senior communications associate": "Senior Communications Associate",
    "graphic designer": "Graphic Designer", "senior graphic designer": "Senior Graphic Designer",
    "editor": "Editor", "editor (books)": "Editor", "senior editor": "Senior Editor",
    "managing editor": "Managing Editor", "production editor": "Production Editor",
    "news editor": "News Editor", "reporter": "Reporter", "content writer": "Content Writer",
    "senior technical writer": "Senior Technical Writer",

    "project manager": "Project Manager", "senior project manager": "Senior Project Manager",
    "technical project manager": "Technical Project Manager",
    "junior project manager": "Junior Project Manager", "project coordinator": "Project Coordinator",
    "program manager": "Program Manager", "program manager (staff)": "Program Manager",
    "program coordinator": "Program Coordinator", "program analyst": "Program Analyst",
    "program officer": "Program Officer", "product manager": "Product Manager",
    "senior product manager": "Senior Product Manager", "junior product manager": "Junior Product Manager",
    "operations manager": "Operations Manager", "director of operations": "Director of Operations",
    "customer success manager": "Customer Success Manager",
    "customer service representative": "Customer Service Representative",
    "customer support representative": "Customer Support Representative",
    "account manager": "Account Manager", "accounts manager": "Account Manager",

    "director": "Director", "associate director": "Associate Director",
    "assistant director": "Assistant Director", "assistant director, communications": "Assistant Director, Communications",
    "director of development": "Director of Development", "executive director": "Executive Director",
    "program director": "Program Director", "senior director": "Senior Director",
    "manager": "Manager", "senior manager": "Senior Manager", "supervisor": "Supervisor",
    "consultant": "Consultant", "senior consultant": "Senior Consultant",
    "analyst": "Analyst", "senior analyst": "Senior Analyst", "business analyst": "Business Analyst",
    "research analyst": "Research Analyst", "policy analyst": "Policy Analyst",
    "associate": "Associate", "senior associate": "Senior Associate", "research associate": "Research Associate",
    "engineer": "Engineer", "senior engineer": "Senior Engineer", "partner": "Partner",
    "senior vice president": "Senior Vice President",
}

t = df["job_title"].str.strip().str.replace(r"\s+", " ", regex=True)
df["job_title"] = t.str.lower().map(title_map).fillna(t)

In [1999]:
race_map = {
    "Hispanic, Latino, or Spanish origin, White": "Hispanic, Latino, or Spanish origin",
    "Asian or Asian American, White": "Asian or Asian American",
    "Black or African American, White": "Black or African American",
    "Middle Eastern or Northern African, White": "Middle Eastern or Northern African",
    "Native American or Alaska Native, White": "Native American or Alaska Native",

    "Another option not listed here or prefer not to answer": "Other or prefer not to answer",
    "Other": "Other or prefer not to answer",
}

df["race"] = df["race"].str.strip().replace(race_map)
print(df["race"].value_counts(dropna=False))

race
White                                  22784
Asian or Asian American                 1647
Other or prefer not to answer           1225
Hispanic, Latino, or Spanish origin      938
Black or African American                767
Name: count, dtype: int64

In [2000]:
age_order = ["under 18", "18-24", "25-34", "35-44", "45-54", "55-64", "65 or over"]
exp_order = ["1 year or less", "2 - 4 years", "5 - 7 years", "8 - 10 years",
             "11 - 20 years", "21 - 30 years", "31 - 40 years", "41 years or more"]
edu_order = ["High School", "College unfinished", "College degree",
             "Master's degree", "Professional degree (MD, JD, etc.)", "PhD"]

for c, order in[("age", age_order),
                ("exp_overall", exp_order),
                ("exp_field", exp_order),
                ("education", edu_order)]:
    df[f"{c}_rank"] = df[c].map({v: i + 1 for i, v in enumerate(order)})
    missing = df.loc[df[f"{c}_rank"].isna() & df[c].notna(), c].unique()
    print(c, "|missing ranks: ", list(missing))

age |missing ranks:  []
exp_overall |missing ranks:  []
exp_field |missing ranks:  []
education |missing ranks:  []

In [2001]:
df["industry"] = df["industry"].fillna("Unknown")

In [2002]:
df.to_csv("ask_a_manager_clean.csv", index=False, encoding="utf-8-sig")

In [2003]:
descriptions = {
    "job_title": ("Job title as reported by the respondent",
                  "Whitespace and capitalization standardized; common variants merged"),
    "job_family": ("Job function group (e.g. Software & IT, Education & Library)",
                   "Derived with keyword rules on job_title"),
    "seniority": ("Seniority level (Individual contributor, Senior, Manager, Director+)",
                  "Derived with keyword rules on job_title"),
    "industry": ("Industry of the employer", "Categories with 100 rows or fewer grouped as 'Other'"),
    "age": ("Age range of the respondent", "Original categories kept"),
    "age_rank": ("Sort order for age", "Integer used for 'Sort by column' in Power BI"),
    "exp_overall": ("Total years of professional experience", "Range format standardized"),
    "exp_overall_rank": ("Sort order for exp_overall", "Integer used for 'Sort by column' in Power BI"),
    "exp_field": ("Years of professional experience in the respondent's field", "Range format standardized"),
    "exp_field_rank": ("Sort order for exp_field", "Integer used for 'Sort by column' in Power BI"),
    "education": ("Highest level of education completed",
                  "'Some college' renamed to 'College unfinished'"),
    "education_rank": ("Sort order for education", "Integer used for 'Sort by column' in Power BI"),
    "gender": ("Gender reported by the respondent",
               "'Prefer not to answer' merged into 'Other or prefer not to answer'"),
    "race": ("Race/ethnicity reported by the respondent",
             "Multi-select combinations including 'White' simplified; small categories grouped as 'Other'"),
    "country": ("Country of work",
                "Standardized with pycountry, manual aliases and fuzzy matching; categories with 100 rows or fewer grouped as 'Other'"),
    "state": ("US state of work",
              "'Non-US' if working outside the US; 'Unknown' if US without a state; Washington D.C. variants unified; categories with 100 rows or fewer grouped as 'Other'"),
    "city": ("City of work", "Variants unified with a replacement dictionary; non-answers set to null"),
    "currency_original": ("Currency in which the salary was reported", "'AUD/NZD' split into AUD or NZD using the country"),
    "salary_local": ("Annual salary in the original currency", "Converted from text to number"),
    "additional_comp_local": ("Bonuses or overtime in an average year, original currency",
                              "Null means the question was left blank"),
    "salary_usd": ("Annual salary converted to USD",
                   "Converted with the ECB rate (Frankfurter API) on the response date; outliers filtered"),
    "additional_comp_usd": ("Additional compensation converted to USD",
                            "Outliers set to null"),
    "total_comp_usd": ("salary_usd + additional_comp_usd (nulls treated as 0)", "Calculated"),
    "salary_rescaled": ("True if the original salary looked like it was in thousands and was multiplied by 1,000",
                        "Flag kept for transparency"),
}

dd = pd.DataFrame({"column": df.columns, "dtype": df.dtypes.astype(str).values})
dd["description"] = dd["column"].map(lambda c: descriptions.get(c, ("", ""))[0])
dd["cleaning_applied"] = dd["column"].map(lambda c: descriptions.get(c, ("", ""))[1])

print("Columns without a description:", dd.loc[dd["description"] == "", "column"].tolist())

dd.to_csv("data_dictionary.csv", index=False, encoding="utf-8-sig")
dd

Columns without a description: ['Timestamp']

,column,dtype,description,cleaning_applied
0,Timestamp,str,,
1,age,str,Age range of the respondent,Original categories kept
2,job_title,str,Job title as reported by the respondent,Whitespace and capitalization standardized; co...
3,additional_comp_local,float64,"Bonuses or overtime in an average year, origin...",Null means the question was left blank
4,state,str,US state of work,'Non-US' if working outside the US; 'Unknown' ...
5,city,str,City of work,Variants unified with a replacement dictionary...
6,exp_overall,str,Total years of professional experience,Range format standardized
7,exp_field,str,Years of professional experience in the respon...,Range format standardized
8,education,str,Highest level of education completed,'Some college' renamed to 'College unfinished'
9,gender,str,Gender reported by the respondent,'Prefer not to answer' merged into 'Other or p...
10,race,str,Race/ethnicity reported by the respondent,Multi-select combinations including 'White' si...
11,country,str,Country of work,"Standardized with pycountry, manual aliases an..."
12,currency_original,str,Currency in which the salary was reported,'AUD/NZD' split into AUD or NZD using the country
13,salary_local,int64,Annual salary in the original currency,Converted from text to number
14,job_family,str,"Job function group (e.g. Software & IT, Educat...",Derived with keyword rules on job_title
15,salary_usd,float64,Annual salary converted to USD,Converted with the ECB rate (Frankfurter API) ...
16,additional_comp_usd,float64,Additional compensation converted to USD,Outliers set to null
17,total_comp_usd,float64,salary_usd + additional_comp_usd (nulls treate...,Calculated
18,industry,str,Industry of the employer,Categories with 100 rows or fewer grouped as '...
19,age_rank,int64,Sort order for age,Integer used for 'Sort by column' in Power BI
20,exp_overall_rank,int64,Sort order for exp_overall,Integer used for 'Sort by column' in Power BI
21,exp_field_rank,int64,Sort order for exp_field,Integer used for 'Sort by column' in Power BI
22,education_rank,float64,Sort order for education,Integer used for 'Sort by column' in Power BI

In [2004]:
df.shape

(27361, 23)

In [2005]:
df.columns

Index(['Timestamp', 'age', 'job_title', 'additional_comp_local', 'state',
       'city', 'exp_overall', 'exp_field', 'education', 'gender', 'race',
       'country', 'currency_original', 'salary_local', 'job_family',
       'salary_usd', 'additional_comp_usd', 'total_comp_usd', 'industry',
       'age_rank', 'exp_overall_rank', 'exp_field_rank', 'education_rank'],
      dtype='str')